# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

################################################################################################
################################################################################################
##########                              Parallel Data                            ###############
################################################################################################
################################################################################################


#Seeding categories #11 element
Category.create [{:name => 'Hightech', :slug => 'hightech', :parent_id => '0'}, #1

                 {:name => 'Phones', :slug => 'phones', :parent_id => '1'}, #2
                 {:name => 'Tablets', :slug => 'tablets', :parent_id => '1'},
                 {:name => 'Cameras', :slug => 'cameras', :parent_id => '1'}, #4
                 {:name => 'Computers', :slug => 'computers', :parent_id => '1'},
                 {:name => 'Consoles', :slug => 'consoles', :parent_id => '1'}, #6


                 {:name => 'Softwares', :slug => 'softwares', :parent_id => '0'},

                 {:name => 'Video Games', :slug => 'video-games', :parent_id => '7'}, #8
                 {:name => 'Programming Languages', :slug => 'programming-languages', :parent_id => '7'},
                 {:name => 'Programming Frameworks', :slug => 'programming-frameworks', :parent_id => '7'}, #10
                 {:name => 'Operating Systems', :slug => 'operating-systems', :parent_id => '7'},
                 {:name => 'Webhosting', :slug => 'webhosting', :parent_id => '7'}, #12
                 {:name => 'Web Browsers', :slug => 'webbrowsers', :parent_id => '7'},



                 {:name => 'Travel and Lifestyle', :slug => 'travel-and-lifestyle', :parent_id => '0'}, #14

                 {:name => 'Hotels', :slug => 'hotels', :parent_id => '14'},
                 {:name => 'Travel Agencies', :slug => 'travel-agencies', :parent_id => '14'}, #16
                 {:name => 'Destinations', :slug => 'destinations', :parent_id => '14'},
                 {:name => 'Airlines', :slug => 'airlines', :parent_id => '14'}, #18


                 {:name => 'Motors', :slug => "motors", :parent_id => '0'},

                 {:name => 'Cars', :slug => 'cars', :parent_id => '19'}, #20
                 {:name => 'Boats', :slug => 'boats', :parent_id => '19'},
                 {:name => 'Motorcycles', :slug => 'Motorcycles', :parent_id => '19'}, #22
                 {:name => 'Car Insurances', :slug => 'car-insurances', :parent_id => '19'},
                 {:name => 'Tractors', :slug => 'tractors', :parent_id => '19'}, #24
                 {:name => 'Engines', :slug => 'Engines', :parent_id => '19'}]


#seeding continents
Continent.create [{:name => 'Africa'},
                  {:name => 'Antarctica'},
                  {:name => 'Asia'},
                  {:name => 'Australia'},
                  {:name => 'Europe'},
                  {:name => 'North America'},
                  {:name => 'South America'}]

#Seeding countries
Country.create [{:name => 'Andorra', :continent_id => 5},
                {:name => 'United Arab Emirates', :continent_id => 3},
                {:name => 'Afghanistan', :continent_id => 3},
                {:name => 'Antigua and Barbuda', :continent_id => 7},
                {:name => 'Anguilla', :continent_id => 1},
                {:name => 'Albania', :continent_id => 5},
                {:name => 'Armenia', :continent_id => 3},
                {:name => 'Netherlands Antilles', :continent_id => 5},
                {:name => 'Angola', :continent_id => 1},
                {:name => 'Antarctica', :continent_id => 5},
                {:name => 'Argentina', :continent_id => 7},
                {:name => 'American Samoa', :continent_id => 4},
                {:name => 'Austria', :continent_id => 5},
                {:name => 'Australia', :continent_id => 4},
                {:name => 'Aruba', :continent_id => 6},
                {:name => 'Aland Islands', :continent_id => 5},
                {:name => 'Azerbaijan', :continent_id => 3},
                {:name => 'Bosnia and Herzegovina', :continent_id => 5},
                {:name => 'Barbados', :continent_id => 7},
                {:name => 'Bangladesh', :continent_id => 3},
                {:name => 'Belgium', :continent_id => 5},
                {:name => 'Burkina Faso', :continent_id => 1},
                {:name => 'Bulgaria', :continent_id => 5},
                {:name => 'Bahrain', :continent_id => 3},
                {:name => 'Burundi', :continent_id => 1},
                {:name => 'Benin', :continent_id => 1},
                {:name => 'Saint Barthelemy', :continent_id => 7},
                {:name => 'Bermuda', :continent_id => 6},
                {:name => 'Brunei', :continent_id => 3},
                {:name => 'Bolivia', :continent_id => 7},
                {:name => 'British Antarctic Territory', :continent_id => 2},
                {:name => 'Brazil', :continent_id => 7},
                {:name => 'Bahamas', :continent_id => 7},
                {:name => 'Bhutan', :continent_id => 3},
                {:name => 'Bouvet Island', :continent_id => 2},
                {:name => 'Botswana', :continent_id => 1},
                {:name => 'Belarus', :continent_id => 5},
                {:name => 'Belize', :continent_id => 7},
                {:name => 'Canada', :continent_id => 6},
                {:name => 'Cocos [Keeling] Islands', :continent_id => 3},
                {:name => 'Congo - Kinshasa', :continent_id => 1},
                {:name => 'Central African Republic', :continent_id => 1},
                {:name => 'Congo - Brazzaville', :continent_id => 1},
                {:name => 'Switzerland', :continent_id => 5},
                {:name => 'Cote d\'Ivoire', :continent_id => 1},
                {:name => 'Cook Islands', :continent_id => 4},
                {:name => 'Chile', :continent_id => 7},
                {:name => 'Cameroon', :continent_id => 1},
                {:name => 'China', :continent_id => 3},
                {:name => 'Colombia', :continent_id => 7},
                {:name => 'Costa Rica', :continent_id => 7},
                {:name => 'Serbia and Montenegro', :continent_id => 5},
                {:name => 'Canton and Enderbury Islands', :continent_id => 3},
                {:name => 'Cuba', :continent_id => 7},
                {:name => 'Cape Verde', :continent_id => 1},
                {:name => 'Christmas Island', :continent_id => 4},
                {:name => 'Cyprus', :continent_id => 5},
                {:name => 'Czech Republic', :continent_id => 5},
                {:name => 'East Germany', :continent_id => 5},
                {:name => 'Germany', :continent_id => 5},
                {:name => 'Djibouti', :continent_id => 1},
                {:name => 'Denmark', :continent_id => 5},
                {:name => 'Dominica', :continent_id => 6},
                {:name => 'Dominican Republic', :continent_id => 6},
                {:name => 'Algeria', :continent_id => 1},
                {:name => 'Ecuador', :continent_id => 7},
                {:name => 'Estonia', :continent_id => 5},
                {:name => 'Egypt', :continent_id => 1},
                {:name => 'Western Sahara', :continent_id => 1},
                {:name => 'Eritrea', :continent_id => 1},
                {:name => 'Spain', :continent_id => 5},
                {:name => 'Ethiopia', :continent_id => 1},
                {:name => 'Finland', :continent_id => 5},
                {:name => 'Fiji', :continent_id => 3},
                {:name => 'Falkland Islands', :continent_id => 7},
                {:name => 'Micronesia', :continent_id => 1},
                {:name => 'Faroe Islands', :continent_id => 5},
                {:name => 'French Southern and Antarctic Territories', :continent_id => 2},
                {:name => 'France', :continent_id => 5},
                {:name => 'Metropolitan France', :continent_id => 5},
                {:name => 'Gabon', :continent_id => 1},
                {:name => 'United Kingdom', :continent_id => 5},
                {:name => 'Grenada', :continent_id => 7},
                {:name => 'Georgia', :continent_id => 5},
                {:name => 'French Guiana', :continent_id => 1},
                {:name => 'Guernsey', :continent_id => 5},
                {:name => 'Ghana', :continent_id => 1},
                {:name => 'Gibraltar', :continent_id => 5},
                {:name => 'Greenland', :continent_id => 6},
                {:name => 'Gambia', :continent_id => 1},
                {:name => 'Guinea', :continent_id => 1},
                {:name => 'Guadeloupe', :continent_id => 7},
                {:name => 'Equatorial Guinea', :continent_id => 1},
                {:name => 'Greece', :continent_id => 5},
                {:name => 'South Georgia and the South Sandwich Islands', :continent_id => 7},
                {:name => 'Guatemala', :continent_id => 6},
                {:name => 'Guam', :continent_id => 6},
                {:name => 'Guinea-Bissau', :continent_id => 1},
                {:name => 'Guyana', :continent_id => 7},
                {:name => 'Hong Kong SAR China', :continent_id => 3},
                {:name => 'Heard Island and McDonald Islands', :continent_id => 2},
                {:name => 'Honduras', :continent_id => 6},
                {:name => 'Croatia', :continent_id => 5},
                {:name => 'Haiti', :continent_id => 7},
                {:name => 'Hungary', :continent_id => 5},
                {:name => 'Indonesia', :continent_id => 3},
                {:name => 'Ireland', :continent_id => 5},
                {:name => 'Israel', :continent_id => 5},
                {:name => 'Isle of Man', :continent_id => 5},
                {:name => 'India', :continent_id => 3},
                {:name => 'British Indian Ocean Territory', :continent_id => 3},
                {:name => 'Iraq', :continent_id => 3},
                {:name => 'Iran', :continent_id => 3},
                {:name => 'Iceland', :continent_id => 5},
                {:name => 'Italy', :continent_id => 5},
                {:name => 'Jersey', :continent_id => 5},
                {:name => 'Jamaica', :continent_id => 6},
                {:name => 'Jordan', :continent_id => 3},
                {:name => 'Japan', :continent_id => 3},
                {:name => 'Johnston Island', :continent_id => 6},
                {:name => 'Kenya', :continent_id => 1},
                {:name => 'Kyrgyzstan', :continent_id => 3},
                {:name => 'Cambodia', :continent_id => 3},
                {:name => 'Kiribati', :continent_id => 6},
                {:name => 'Comoros', :continent_id => 1},
                {:name => 'Saint Kitts and Nevis', :continent_id => 6},
                {:name => 'North Korea', :continent_id => 3},
                {:name => 'South Korea', :continent_id => 3},
                {:name => 'Kuwait', :continent_id => 3},
                {:name => 'Cayman Islands', :continent_id => 6},
                {:name => 'Kazakhstan', :continent_id => 3},
                {:name => 'Laos', :continent_id => 3},
                {:name => 'Lebanon', :continent_id => 3},
                {:name => 'Saint Lucia', :continent_id => 7},
                {:name => 'Liechtenstein', :continent_id => 5},
                {:name => 'Sri Lanka', :continent_id => 3},
                {:name => 'Liberia', :continent_id => 1},
                {:name => 'Lesotho', :continent_id => 1},
                {:name => 'Lithuania', :continent_id => 5},
                {:name => 'Luxembourg', :continent_id => 5},
                {:name => 'Latvia', :continent_id => 5},
                {:name => 'Libya', :continent_id => 1},
                {:name => 'Morocco', :continent_id => 1},
                {:name => 'Monaco', :continent_id => 5},
                {:name => 'Moldova', :continent_id => 5},
                {:name => 'Montenegro', :continent_id => 5},
                {:name => 'Saint Martin', :continent_id => 6},
                {:name => 'Madagascar', :continent_id => 1},
                {:name => 'Marshall Islands', :continent_id => 4},
                {:name => 'Midway Islands', :continent_id => 4},
                {:name => 'Macedonia', :continent_id => 5},
                {:name => 'Mali', :continent_id => 1},
                {:name => 'Myanmar [Burma]', :continent_id => 3},
                {:name => 'Mongolia', :continent_id => 5},
                {:name => 'Macau SAR China', :continent_id => 3},
                {:name => 'Northern Mariana Islands', :continent_id => 3},
                {:name => 'Martinique', :continent_id => 6},
                {:name => 'Mauritania', :continent_id => 1},
                {:name => 'Montserrat', :continent_id => 6},
                {:name => 'Malta', :continent_id => 5},
                {:name => 'Mauritius', :continent_id => 1},
                {:name => 'Maldives', :continent_id => 3},
                {:name => 'Malawi', :continent_id => 1},
                {:name => 'Mexico', :continent_id => 6},
                {:name => 'Malaysia', :continent_id => 3},
                {:name => 'Mozambique', :continent_id => 1},
                {:name => 'Namibia', :continent_id => 1},
                {:name => 'New Caledonia', :continent_id => 4},
                {:name => 'Niger', :continent_id => 1},
                {:name => 'Norfolk Island', :continent_id => 4},
                {:name => 'Nigeria', :continent_id => 1},
                {:name => 'Nicaragua', :continent_id => 6},
                {:name => 'Netherlands', :continent_id => 5},
                {:name => 'Norway', :continent_id => 5},
                {:name => 'Nepal', :continent_id => 3},
                {:name => 'Dronning Maud Land', :continent_id => 2},
                {:name => 'Nauru', :continent_id => 4},
                {:name => 'Neutral Zone'},
                {:name => 'Niue', :continent_id => 4},
                {:name => 'New Zealand', :continent_id => 4},
                {:name => 'Oman', :continent_id => 3},
                {:name => 'Panama', :continent_id => 7},
                {:name => 'Pacific Islands Trust Territory', :continent_id => 3},
                {:name => 'Peru', :continent_id => 7},
                {:name => 'French Polynesia', :continent_id => 4},
                {:name => 'Papua New Guinea', :continent_id => 1},
                {:name => 'Philippines', :continent_id => 3},
                {:name => 'Pakistan', :continent_id => 3},
                {:name => 'Poland', :continent_id => 5},
                {:name => 'Saint Pierre and Miquelon', :continent_id => 6},
                {:name => 'Pitcairn Islands', :continent_id => 7},
                {:name => 'Puerto Rico', :continent_id => 6},
                {:name => 'Palestinian Territories', :continent_id => 3},
                {:name => 'Portugal', :continent_id => 5},
                {:name => 'U.S. Miscellaneous Pacific Islands', :continent_id => 6},
                {:name => 'Palau', :continent_id => 3},
                {:name => 'Paraguay', :continent_id => 7},
                {:name => 'Panama Canal Zone', :continent_id => 7},
                {:name => 'Qatar', :continent_id => 3},
                {:name => 'Reunion', :continent_id => 1},
                {:name => 'Romania', :continent_id => 5},
                {:name => 'Serbia', :continent_id => 5},
                {:name => 'Russia', :continent_id => 5},
                {:name => 'Rwanda', :continent_id => 1},
                {:name => 'Saudi Arabia', :continent_id => 3},
                {:name => 'Solomon Islands', :continent_id => 4},
                {:name => 'Seychelles', :continent_id => 1},
                {:name => 'Sudan', :continent_id => 1},
                {:name => 'Sweden', :continent_id => 5},
                {:name => 'Singapore', :continent_id => 3},
                {:name => 'Saint Helena', :continent_id => 1},
                {:name => 'Slovenia', :continent_id => 5},
                {:name => 'Svalbard and Jan Mayen', :continent_id => 5},
                {:name => 'Slovakia', :continent_id => 5},
                {:name => 'Sierra Leone', :continent_id => 1},
                {:name => 'San Marino', :continent_id => 5},
                {:name => 'Senegal', :continent_id => 1},
                {:name => 'Somalia', :continent_id => 1},
                {:name => 'Suriname', :continent_id => 7},
                {:name => 'Sao Tome and Principe', :continent_id => 1},
                {:name => 'Union of Soviet Socialist Republics', :continent_id => 5},
                {:name => 'El Salvador', :continent_id => 6},
                {:name => 'Syria', :continent_id => 3},
                {:name => 'Swaziland', :continent_id => 1},
                {:name => 'Turks and Caicos Islands', :continent_id => 6},
                {:name => 'Chad', :continent_id => 1},
                {:name => 'French Southern Territories', :continent_id => 1},
                {:name => 'Togo', :continent_id => 1},
                {:name => 'Thailand', :continent_id => 3},
                {:name => 'Tajikistan', :continent_id => 3},
                {:name => 'Tokelau', :continent_id => 4},
                {:name => 'Timor-Leste', :continent_id => 3},
                {:name => 'Turkmenistan', :continent_id => 3},
                {:name => 'Tunisia', :continent_id => 1},
                {:name => 'Tonga', :continent_id => 4},
                {:name => 'Turkey', :continent_id => 3},
                {:name => 'Trinidad and Tobago', :continent_id => 7},
                {:name => 'Tuvalu', :continent_id => 4},
                {:name => 'Taiwan', :continent_id => 3},
                {:name => 'Tanzania', :continent_id => 1},
                {:name => 'Ukraine', :continent_id => 5},
                {:name => 'Uganda', :continent_id => 1},
                {:name => 'U.S. Minor Outlying Islands', :continent_id => 6},
                {:name => 'United States', :continent_id => 6},
                {:name => 'Uruguay', :continent_id => 7},
                {:name => 'Uzbekistan', :continent_id => 3},
                {:name => 'Vatican City', :continent_id => 5},
                {:name => 'Saint Vincent and the Grenadines', :continent_id => 6},
                {:name => 'North Vietnam', :continent_id => 3},
                {:name => 'Venezuela', :continent_id => 7},
                {:name => 'British Virgin Islands', :continent_id => 6},
                {:name => 'U.S. Virgin Islands', :continent_id => 6},
                {:name => 'Vietnam', :continent_id => 3},
                {:name => 'Vanuatu', :continent_id => 4},
                {:name => 'Wallis and Futuna', :continent_id => 4},
                {:name => 'Wake Island', :continent_id => 6},
                {:name => 'Samoa', :continent_id => 4},
                {:name => 'People\'s Democratic Republic of Yemen', :continent_id => 3},
                {:name => 'Yemen', :continent_id => 3},
                {:name => 'Mayotte', :continent_id => 1},
                {:name => 'South Africa', :continent_id => 1},
                {:name => 'Zambia', :continent_id => 1},
                {:name => 'Zimbabwe', :continent_id => 1}]


################################################################################################
################################################################################################
##########                              Products Data                            ###############
################################################################################################
################################################################################################



#Seeding Manufacturers
Manufacturer.create [{ :name => 'Samsung', :slug => 'samsung', :contact_email => 'contact@samsung.com', :country_id => '127'},
					{ :name => 'Sony', :slug => 'sony', :contact_email => 'contact@sony.com', :country_id => '119'}]


#Seeding Products
Product.create [{ :name => 'Galaxy S3', :slug => 'galaxy-s3', :refname => 'GT-I9300', :released_at => '2012-05-01', :long_desc => 'The most powerful smartphone on earth', :manufacturer_id => '1', :category_id => '2'},
                { :name => 'Galaxy S2', :slug => 'galaxy-s2', :refname => 'GT-I9100', :released_at => '2011-05-01', :long_desc => 'The thinnest smartphone on earth', :manufacturer_id => '1', :category_id => '2'}] #2



################################################################################################
################################################################################################
##########                         Operating systems Data                        ###############
################################################################################################
################################################################################################



Product.create [{:name => "Unicos", :refname => "Unicos", :slug => "Unicos", :category_id => "11"},
{:name => "OS/8", :refname => "OS/8", :slug => "OS/8", :category_id => "11"},
{:name => "Ultrix", :refname => "Ultrix", :slug => "Ultrix", :category_id => "11"},
{:name => "Ubuntu JeOS", :refname => "Ubuntu JeOS", :slug => "Ubuntu JeOS", :category_id => "11"},
{:name => "Idris", :refname => "Idris", :slug => "Idris", :category_id => "11"},
{:name => "Linux-based devices", :refname => "Linux-based devices", :slug => "Linux-based devices", :category_id => "11"},
{:name => "Absolute", :refname => "Absolute", :slug => "Absolute", :category_id => "11"},
{:name => "Damn Small Linux", :refname => "Damn Small Linux", :slug => "Damn Small Linux", :category_id => "11"},
{:name => "MS-DOS 2.0", :refname => "MS-DOS 2.0", :slug => "MS-DOS 2.0", :released_at => "1983", :category_id => "11"},
{:name => "S60 platform", :refname => "S60 platform", :slug => "S60 platform", :category_id => "11"},
{:name => "VM", :refname => "VM", :slug => "VM", :category_id => "11"},
{:name => "Mac OS", :refname => "Mac OS", :slug => "Mac OS", :released_at => "1984", :category_id => "11"},
{:name => "TinyKRNL", :refname => "TinyKRNL", :slug => "TinyKRNL", :category_id => "11"},
{:name => "Kubuntu", :refname => "Kubuntu", :slug => "Kubuntu", :released_at => "2006", :category_id => "11"},
{:name => "Super OS", :refname => "Super OS", :slug => "Super OS", :category_id => "11"},
{:name => "Tru64 UNIX", :refname => "Tru64 UNIX", :slug => "Tru64 UNIX", :category_id => "11"},
{:name => "Windows Vista Business", :refname => "Windows Vista Business", :slug => "Windows Vista Business", :category_id => "11"},
{:name => "Ubuntu Studio", :refname => "Ubuntu Studio", :slug => "Ubuntu Studio", :category_id => "11"},
{:name => "ChibiOS/RT", :refname => "ChibiOS/RT", :slug => "ChibiOS/RT", :category_id => "11"},
{:name => "Apple DOS", :refname => "Apple DOS", :slug => "Apple DOS", :category_id => "11"},
{:name => "Cisco IOS", :refname => "Cisco IOS", :slug => "Cisco IOS", :category_id => "11"},
{:name => "Windows Phone 7.1", :refname => "Windows Phone 7.1", :slug => "Windows Phone 7.1", :category_id => "11"},
{:name => "Syllable", :refname => "Syllable", :slug => "Syllable", :category_id => "11"},
{:name => "Windows Phone 8", :refname => "Windows Phone 8", :slug => "Windows Phone 8", :category_id => "11"},
{:name => "Freeware", :refname => "Freeware", :slug => "Freeware", :category_id => "11"},
{:name => "DOS/VS", :refname => "DOS/VS", :slug => "DOS/VS", :category_id => "11"},
{:name => "RT-Thread", :refname => "RT-Thread", :slug => "RT-Thread", :category_id => "11"},
{:name => "Rocks Cluster Distribution", :refname => "Rocks Cluster Distribution", :slug => "Rocks Cluster Distribution", :category_id => "11"},
{:name => "Whitix", :refname => "Whitix", :slug => "Whitix", :category_id => "11"},
{:name => "MIE Linux", :refname => "MIE Linux", :slug => "MIE Linux", :released_at => "2008", :category_id => "11"},
{:name => "Ubuntu 9.10", :refname => "Ubuntu 9.10", :slug => "Ubuntu 9.10", :released_at => "2009", :category_id => "11"},
{:name => "Linux", :refname => "Linux", :slug => "Linux", :category_id => "11"},
{:name => "Aurora SPARC Linux", :refname => "Aurora SPARC Linux", :slug => "Aurora SPARC Linux", :category_id => "11"},
{:name => "Windows 98", :refname => "Windows 98", :slug => "Windows 98", :category_id => "11"},
{:name => "SLAX", :refname => "SLAX", :slug => "SLAX", :released_at => "2006", :category_id => "11"},
{:name => "IS-DOS", :refname => "IS-DOS", :slug => "IS-DOS", :category_id => "11"},
{:name => "Mac OS X v10.1", :refname => "Mac OS X v10.1", :slug => "Mac OS X v10.1", :released_at => "2001", :category_id => "11"},
{:name => "Fusion RTOS", :refname => "Fusion RTOS", :slug => "Fusion RTOS", :category_id => "11"},
{:name => "Ultimate Edition", :refname => "Ultimate Edition", :slug => "Ultimate Edition", :category_id => "11"},
{:name => "Nokia 9210", :refname => "Nokia 9210", :slug => "Nokia 9210", :category_id => "11"},
{:name => "Windows Server 2008 for Itanium-based Systems", :refname => "Windows Server 2008 for Itanium-based Systems", :slug => "Windows Server 2008 for Itanium-based Systems", :category_id => "11"},
{:name => "Berkeley Timesharing System", :refname => "Berkeley Timesharing System", :slug => "Berkeley Timesharing System", :category_id => "11"},
{:name => "Parted Magic", :refname => "Parted Magic", :slug => "Parted Magic", :category_id => "11"},
{:name => "Vector Linux", :refname => "Vector Linux", :slug => "Vector Linux", :released_at => "2006", :category_id => "11"},
{:name => "Argante", :refname => "Argante", :slug => "Argante", :category_id => "11"},
{:name => "Elive", :refname => "Elive", :slug => "Elive", :category_id => "11"},
{:name => "VM/386", :refname => "VM/386", :slug => "VM/386", :category_id => "11"},
{:name => "GoblinX", :refname => "GoblinX", :slug => "GoblinX", :category_id => "11"},
{:name => "SUSE Linux Enterprise Server", :refname => "SUSE Linux Enterprise Server", :slug => "SUSE Linux Enterprise Server", :category_id => "11"},
{:name => "Kubuntu 11.04", :refname => "Kubuntu 11.04", :slug => "Kubuntu 11.04", :category_id => "11"},
{:name => "Windows Server 2012", :refname => "Windows Server 2012", :slug => "Windows Server 2012", :released_at => "2012", :category_id => "11"},
{:name => "CP-823/U", :refname => "CP-823/U", :slug => "CP-823/U", :category_id => "11"},
{:name => "UNIX System V", :refname => "UNIX System V", :slug => "UNIX System V", :category_id => "11"},
{:name => "MEPIS", :refname => "MEPIS", :slug => "MEPIS", :released_at => "2009", :category_id => "11"},
{:name => "Foresight Linux", :refname => "Foresight Linux", :slug => "Foresight Linux", :released_at => "2007", :category_id => "11"},
{:name => "Mac OS X v10.6", :refname => "Mac OS X v10.6", :slug => "Mac OS X v10.6", :released_at => "2009", :category_id => "11"},
{:name => "Cray Operating System", :refname => "Cray Operating System", :slug => "Cray Operating System", :category_id => "11"},
{:name => "Windows Web Server 2008", :refname => "Windows Web Server 2008", :slug => "Windows Web Server 2008", :category_id => "11"},
{:name => "Research Unix", :refname => "Research Unix", :slug => "Research Unix", :category_id => "11"},
{:name => "Windows NT", :refname => "Windows NT", :slug => "Windows NT", :released_at => "1993", :category_id => "11"},
{:name => "Multics", :refname => "Multics", :slug => "Multics", :category_id => "11"},
{:name => "GP2X Wiz", :refname => "GP2X Wiz", :slug => "GP2X Wiz", :category_id => "11"},
{:name => "E/OS", :refname => "E/OS", :slug => "E/OS", :category_id => "11"},
{:name => "Windows Storage Server 2008", :refname => "Windows Storage Server 2008", :slug => "Windows Storage Server 2008", :category_id => "11"},
{:name => "Newton OS", :refname => "Newton OS", :slug => "Newton OS", :category_id => "11"},
{:name => "BSD/OS", :refname => "BSD/OS", :slug => "BSD/OS", :category_id => "11"},
{:name => "FreeBSD 2.1.5", :refname => "FreeBSD 2.1.5", :slug => "FreeBSD 2.1.5", :category_id => "11"},
{:name => "TR-DOS", :refname => "TR-DOS", :slug => "TR-DOS", :category_id => "11"},
{:name => "GP2X", :refname => "GP2X", :slug => "GP2X", :category_id => "11"},
{:name => "FMI/OS", :refname => "FMI/OS", :slug => "FMI/OS", :category_id => "11"},
{:name => "DEC BATCH-11/DOS-11", :refname => "DEC BATCH-11/DOS-11", :slug => "DEC BATCH-11/DOS-11", :category_id => "11"},
{:name => "Yellow Dog Linux", :refname => "Yellow Dog Linux", :slug => "Yellow Dog Linux", :category_id => "11"},
{:name => "86-DOS", :refname => "86-DOS", :slug => "86-DOS", :category_id => "11"},
{:name => "AD-75", :refname => "AD-75", :slug => "AD-75", :category_id => "11"},
{:name => "Maemo", :refname => "Maemo", :slug => "Maemo", :category_id => "11"},
{:name => "TUD:OS", :refname => "TUD:OS", :slug => "TUD:OS", :category_id => "11"},
{:name => "SymbOS", :refname => "SymbOS", :slug => "SymbOS", :category_id => "11"},
{:name => "BKUNIX", :refname => "BKUNIX", :slug => "BKUNIX", :category_id => "11"},
{:name => "Atomix", :refname => "Atomix", :slug => "Atomix", :category_id => "11"},
{:name => "Linkat", :refname => "Linkat", :slug => "Linkat", :category_id => "11"},
{:name => "PC DOS 1.0", :refname => "PC DOS 1.0", :slug => "PC DOS 1.0", :category_id => "11"},
{:name => "Ubuntu Netbook Remix", :refname => "Ubuntu Netbook Remix", :slug => "Ubuntu Netbook Remix", :category_id => "11"},
{:name => "SUPER-UX", :refname => "SUPER-UX", :slug => "SUPER-UX", :category_id => "11"},
{:name => "Slackware", :refname => "Slackware", :slug => "Slackware", :category_id => "11"},
{:name => "Google Chrome OS", :refname => "Google Chrome OS", :slug => "Google Chrome OS", :category_id => "11"},
{:name => "Windows Server 2003", :refname => "Windows Server 2003", :slug => "Windows Server 2003", :released_at => "2003", :category_id => "11"},
{:name => "Windows Server 2008 Enterprise Edition", :refname => "Windows Server 2008 Enterprise Edition", :slug => "Windows Server 2008 Enterprise Edition", :category_id => "11"},
{:name => "ROS", :refname => "ROS", :slug => "ROS", :category_id => "11"},
{:name => "System Software 6", :refname => "System Software 6", :slug => "System Software 6", :released_at => "1988", :category_id => "11"},
{:name => "PC DOS 7.0", :refname => "PC DOS 7.0", :slug => "PC DOS 7.0", :category_id => "11"},
{:name => "Windows 2000 Datacenter Server", :refname => "Windows 2000 Datacenter Server", :slug => "Windows 2000 Datacenter Server", :category_id => "11"},
{:name => "Unix/NS", :refname => "Unix/NS", :slug => "Unix/NS", :category_id => "11"},
{:name => "Gentoo Linux", :refname => "Gentoo Linux", :slug => "Gentoo Linux", :released_at => "2002", :category_id => "11"},
{:name => "Xandros Server", :refname => "Xandros Server", :slug => "Xandros Server", :category_id => "11"},
{:name => "Pintos", :refname => "Pintos", :slug => "Pintos", :category_id => "11"},
{:name => "Plan 9", :refname => "Plan 9", :slug => "Plan 9", :released_at => "1992", :category_id => "11"},
{:name => "JNode", :refname => "JNode", :slug => "JNode", :category_id => "11"},
{:name => "Real-time operating system", :refname => "Real-time operating system", :slug => "Real-time operating system", :category_id => "11"},
{:name => "Derrick Operating System", :refname => "Derrick Operating System", :slug => "Derrick Operating System", :category_id => "11"},
{:name => "Pandora", :refname => "Pandora", :slug => "Pandora", :category_id => "11"},
{:name => "FreeBSD 4.x", :refname => "FreeBSD 4.x", :slug => "FreeBSD 4.x", :category_id => "11"},
{:name => "DOS/360", :refname => "DOS/360", :slug => "DOS/360", :category_id => "11"},
{:name => "FreeBSD 4.8", :refname => "FreeBSD 4.8", :slug => "FreeBSD 4.8", :category_id => "11"},
{:name => "Windows XP Professional x64 Edition", :refname => "Windows XP Professional x64 Edition", :slug => "Windows XP Professional x64 Edition", :category_id => "11"},
{:name => "Windows 3.0", :refname => "Windows 3.0", :slug => "Windows 3.0", :category_id => "11"},
{:name => "SMSall", :refname => "SMSall", :slug => "SMSall", :category_id => "11"},
{:name => "RSX-11", :refname => "RSX-11", :slug => "RSX-11", :category_id => "11"},
{:name => "386BSD", :refname => "386BSD", :slug => "386BSD", :released_at => "1992", :category_id => "11"},
{:name => "Ubuntu 11.04", :refname => "Ubuntu 11.04", :slug => "Ubuntu 11.04", :released_at => "2011", :category_id => "11"},
{:name => "Funtoo", :refname => "Funtoo", :slug => "Funtoo", :category_id => "11"},
{:name => "VA Kernel", :refname => "VA Kernel", :slug => "VA Kernel", :category_id => "11"},
{:name => "RISC OS", :refname => "RISC OS", :slug => "RISC OS", :category_id => "11"},
{:name => "Windows Vista", :refname => "Windows Vista", :slug => "Windows Vista", :released_at => "2007", :category_id => "11"},
{:name => "SharpOS", :refname => "SharpOS", :slug => "SharpOS", :category_id => "11"},
{:name => "Red Hat Enterprise Linux", :refname => "Red Hat Enterprise Linux", :slug => "Red Hat Enterprise Linux", :category_id => "11"},
{:name => "Windows Mobile", :refname => "Windows Mobile", :slug => "Windows Mobile", :category_id => "11"},
{:name => "CRUX", :refname => "CRUX", :slug => "CRUX", :category_id => "11"},
{:name => "Linspire", :refname => "Linspire", :slug => "Linspire", :category_id => "11"},
{:name => "LUnix", :refname => "LUnix", :slug => "LUnix", :category_id => "11"},
{:name => "Apple Pascal", :refname => "Apple Pascal", :slug => "Apple Pascal", :category_id => "11"},
{:name => "Phoenix OS", :refname => "Phoenix OS", :slug => "Phoenix OS", :category_id => "11"},
{:name => "FreeBSD 1.1.5", :refname => "FreeBSD 1.1.5", :slug => "FreeBSD 1.1.5", :category_id => "11"},
{:name => "Windows XP Tablet PC Edition", :refname => "Windows XP Tablet PC Edition", :slug => "Windows XP Tablet PC Edition", :category_id => "11"},
{:name => "VxWorks", :refname => "VxWorks", :slug => "VxWorks", :category_id => "11"},
{:name => "Sinclair BASIC", :refname => "Sinclair BASIC", :slug => "Sinclair BASIC", :category_id => "11"},
{:name => "Kubuntu 6.06 LTS", :refname => "Kubuntu 6.06 LTS", :slug => "Kubuntu 6.06 LTS", :released_at => "2006", :category_id => "11"},
{:name => "GnuLinEx", :refname => "GnuLinEx", :slug => "GnuLinEx", :category_id => "11"},
{:name => "AmigaOS", :refname => "AmigaOS", :slug => "AmigaOS", :category_id => "11"},
{:name => "BBC Micro", :refname => "BBC Micro", :slug => "BBC Micro", :category_id => "11"},
{:name => "Kororaa", :refname => "Kororaa", :slug => "Kororaa", :category_id => "11"},
{:name => "Pentoo", :refname => "Pentoo", :slug => "Pentoo", :category_id => "11"},
{:name => "Ubuntu Buddhist Remix", :refname => "Ubuntu Buddhist Remix", :slug => "Ubuntu Buddhist Remix", :category_id => "11"},
{:name => "CTSS", :refname => "CTSS", :slug => "CTSS", :category_id => "11"},
{:name => "Fedora Core", :refname => "Fedora Core", :slug => "Fedora Core", :released_at => "2003", :category_id => "11"},
{:name => "FreeBSD 1.1", :refname => "FreeBSD 1.1", :slug => "FreeBSD 1.1", :category_id => "11"},
{:name => "Chrysalis", :refname => "Chrysalis", :slug => "Chrysalis", :category_id => "11"},
{:name => "Windows NT 3.1", :refname => "Windows NT 3.1", :slug => "Windows NT 3.1", :released_at => "1993", :category_id => "11"},
{:name => "Windows Server 2000", :refname => "Windows Server 2000", :slug => "Windows Server 2000", :category_id => "11"},
{:name => "Internet Explorer", :refname => "Internet Explorer", :slug => "Internet Explorer", :category_id => "11"},
{:name => "CAos Linux", :refname => "CAos Linux", :slug => "CAos Linux", :category_id => "11"},
{:name => "PC-DOS", :refname => "PC-DOS", :slug => "PC-DOS", :released_at => "1981", :category_id => "11"},
{:name => "Windows XP", :refname => "Windows XP", :slug => "Windows XP", :released_at => "2001", :category_id => "11"},
{:name => "Drupal", :refname => "Drupal", :slug => "Drupal", :category_id => "11"},
{:name => "MS-DOS 4.0", :refname => "MS-DOS 4.0", :slug => "MS-DOS 4.0", :released_at => "1988", :category_id => "11"},
{:name => "Tuga", :refname => "Tuga", :slug => "Tuga", :category_id => "11"},
{:name => "Red Hat Linux", :refname => "Red Hat Linux", :slug => "Red Hat Linux", :category_id => "11"},
{:name => "FreeBSD 2.1", :refname => "FreeBSD 2.1", :slug => "FreeBSD 2.1", :category_id => "11"},
{:name => "Inferno", :refname => "Inferno", :slug => "Inferno", :category_id => "11"},
{:name => "Fedora Core 3", :refname => "Fedora Core 3", :slug => "Fedora Core 3", :category_id => "11"},
{:name => "Windows XP Starter Edition", :refname => "Windows XP Starter Edition", :slug => "Windows XP Starter Edition", :category_id => "11"},
{:name => "PCLinuxOS", :refname => "PCLinuxOS", :slug => "PCLinuxOS", :released_at => "2007", :category_id => "11"},
{:name => "UserLinux", :refname => "UserLinux", :slug => "UserLinux", :category_id => "11"},
{:name => "Mac OS X v10.2", :refname => "Mac OS X v10.2", :slug => "Mac OS X v10.2", :category_id => "11"},
{:name => "Talon DSP RTOS", :refname => "Talon DSP RTOS", :slug => "Talon DSP RTOS", :category_id => "11"},
{:name => "Windows 8", :refname => "Windows 8", :slug => "Windows 8", :category_id => "11"},
{:name => "BeOS", :refname => "BeOS", :slug => "BeOS", :category_id => "11"},
{:name => "Amiga OS 2.0", :refname => "Amiga OS 2.0", :slug => "Amiga OS 2.0", :category_id => "11"},
{:name => "TRON Project", :refname => "TRON Project", :slug => "TRON Project", :released_at => "1984", :category_id => "11"},
{:name => "Native Oberon", :refname => "Native Oberon", :slug => "Native Oberon", :category_id => "11"},
{:name => "OpenVMS", :refname => "OpenVMS", :slug => "OpenVMS", :category_id => "11"},
{:name => "SabayonLinux", :refname => "SabayonLinux", :slug => "SabayonLinux", :category_id => "11"},
{:name => "TOPS-20", :refname => "TOPS-20", :slug => "TOPS-20", :category_id => "11"},
{:name => "FLEX", :refname => "FLEX", :slug => "FLEX", :released_at => "1976", :category_id => "11"},
{:name => "FreeDOS", :refname => "FreeDOS", :slug => "FreeDOS", :category_id => "11"},
{:name => "FreeBSD 2.0.5", :refname => "FreeBSD 2.0.5", :slug => "FreeBSD 2.0.5", :category_id => "11"},
{:name => "Tinix", :refname => "Tinix", :slug => "Tinix", :category_id => "11"},
{:name => "Xandros Desktop", :refname => "Xandros Desktop", :slug => "Xandros Desktop", :category_id => "11"},
{:name => "Minix", :refname => "Minix", :slug => "Minix", :category_id => "11"},
{:name => "OS/360", :refname => "OS/360", :slug => "OS/360", :category_id => "11"},
{:name => "Mona", :refname => "Mona", :slug => "Mona", :category_id => "11"},
{:name => "Kubuntu 9.04", :refname => "Kubuntu 9.04", :slug => "Kubuntu 9.04", :category_id => "11"},
{:name => "DNIX", :refname => "DNIX", :slug => "DNIX", :category_id => "11"},
{:name => "Ntoskrnl.exe", :refname => "Ntoskrnl.exe", :slug => "Ntoskrnl.exe", :category_id => "11"},
{:name => "Web browser", :refname => "Web browser", :slug => "Web browser", :category_id => "11"},
{:name => "Stratus VOS", :refname => "Stratus VOS", :slug => "Stratus VOS", :category_id => "11"},
{:name => "Mac OS X Server", :refname => "Mac OS X Server", :slug => "Mac OS X Server", :category_id => "11"},
{:name => "Windows Vista Ultimate", :refname => "Windows Vista Ultimate", :slug => "Windows Vista Ultimate", :released_at => "2007", :category_id => "11"},
{:name => "Fedora Core 5", :refname => "Fedora Core 5", :slug => "Fedora Core 5", :category_id => "11"},
{:name => "AmiQNX", :refname => "AmiQNX", :slug => "AmiQNX", :category_id => "11"},
{:name => "Amiga", :refname => "Amiga", :slug => "Amiga", :category_id => "11"},
{:name => "PikeOS", :refname => "PikeOS", :slug => "PikeOS", :category_id => "11"},
{:name => "Fluxbuntu", :refname => "Fluxbuntu", :slug => "Fluxbuntu", :category_id => "11"},
{:name => "RC 4000 Multiprogramming System", :refname => "RC 4000 Multiprogramming System", :slug => "RC 4000 Multiprogramming System", :category_id => "11"},
{:name => "Berkeley Software Distribution", :refname => "Berkeley Software Distribution", :slug => "Berkeley Software Distribution", :released_at => "1977", :category_id => "11"},
{:name => "Mozilla Firefox", :refname => "Mozilla Firefox", :slug => "Mozilla Firefox", :category_id => "11"},
{:name => "QNX", :refname => "QNX", :slug => "QNX", :category_id => "11"},
{:name => "UnixWare", :refname => "UnixWare", :slug => "UnixWare", :category_id => "11"},
{:name => "Windows 2000 Advanced Server", :refname => "Windows 2000 Advanced Server", :slug => "Windows 2000 Advanced Server", :category_id => "11"},
{:name => "WebOS", :refname => "WebOS", :slug => "WebOS", :released_at => "2009", :category_id => "11"},
{:name => "MCNLive", :refname => "MCNLive", :slug => "MCNLive", :category_id => "11"},
{:name => "Kayou", :refname => "Kayou", :slug => "Kayou", :category_id => "11"},
{:name => "Contiki", :refname => "Contiki", :slug => "Contiki", :category_id => "11"},
{:name => "Ark Linux", :refname => "Ark Linux", :slug => "Ark Linux", :category_id => "11"},
{:name => "DOS", :refname => "DOS", :slug => "DOS", :category_id => "11"},
{:name => "Fedora Core 2", :refname => "Fedora Core 2", :slug => "Fedora Core 2", :category_id => "11"},
{:name => "Windows 7", :refname => "Windows 7", :slug => "Windows 7", :released_at => "2009", :category_id => "11"},
{:name => "Mandriva Linux", :refname => "Mandriva Linux", :slug => "Mandriva Linux", :category_id => "11"},
{:name => "BeOS R5", :refname => "BeOS R5", :slug => "BeOS R5", :category_id => "11"},
{:name => "HP-UX", :refname => "HP-UX", :slug => "HP-UX", :category_id => "11"},
{:name => "Ubuntu", :refname => "Ubuntu", :slug => "Ubuntu", :released_at => "2004", :category_id => "11"},
{:name => "Windows NT 4.0 Embedded", :refname => "Windows NT 4.0 Embedded", :slug => "Windows NT 4.0 Embedded", :category_id => "11"},
{:name => "TSS-8", :refname => "TSS-8", :slug => "TSS-8", :category_id => "11"},
{:name => "FreeBSD 2.1.7", :refname => "FreeBSD 2.1.7", :slug => "FreeBSD 2.1.7", :category_id => "11"},
{:name => "Kaneton", :refname => "Kaneton", :slug => "Kaneton", :category_id => "11"},
{:name => "Fedora 7", :refname => "Fedora 7", :slug => "Fedora 7", :category_id => "11"},
{:name => "386BSD", :refname => "386BSD", :slug => "386BSD", :category_id => "11"},
{:name => "HydrixOS", :refname => "HydrixOS", :slug => "HydrixOS", :category_id => "11"},
{:name => "SPIN", :refname => "SPIN", :slug => "SPIN", :category_id => "11"},
{:name => "PC-UX", :refname => "PC-UX", :slug => "PC-UX", :category_id => "11"},
{:name => "EVEREST Linux", :refname => "EVEREST Linux", :slug => "EVEREST Linux", :category_id => "11"},
{:name => "ReactOS", :refname => "ReactOS", :slug => "ReactOS", :category_id => "11"},
{:name => "Kubuntu 5.04", :refname => "Kubuntu 5.04", :slug => "Kubuntu 5.04", :released_at => "2005", :category_id => "11"},
{:name => "Trix", :refname => "Trix", :slug => "Trix", :category_id => "11"},
{:name => "Mac OS X Server 1.0", :refname => "Mac OS X Server 1.0", :slug => "Mac OS X Server 1.0", :released_at => "1999", :category_id => "11"},
{:name => "SCO OpenServer", :refname => "SCO OpenServer", :slug => "SCO OpenServer", :category_id => "11"},
{:name => "Kubuntu 7.04", :refname => "Kubuntu 7.04", :slug => "Kubuntu 7.04", :released_at => "2007", :category_id => "11"},
{:name => "Mac OS X", :refname => "Mac OS X", :slug => "Mac OS X", :released_at => "2001", :category_id => "11"},
{:name => "Spring operating system", :refname => "Spring operating system", :slug => "Spring operating system", :category_id => "11"},
{:name => "MSX BASIC", :refname => "MSX BASIC", :slug => "MSX BASIC", :category_id => "11"},
{:name => "Trustix", :refname => "Trustix", :slug => "Trustix", :category_id => "11"},
{:name => "Vanguard microkernel", :refname => "Vanguard microkernel", :slug => "Vanguard microkernel", :category_id => "11"},
{:name => "MS-DOS 7.0", :refname => "MS-DOS 7.0", :slug => "MS-DOS 7.0", :released_at => "1995", :category_id => "11"},
{:name => "Finder", :refname => "Finder", :slug => "Finder", :category_id => "11"},
{:name => "Atari DOS", :refname => "Atari DOS", :slug => "Atari DOS", :category_id => "11"},
{:name => "Mac OS X v10.3", :refname => "Mac OS X v10.3", :slug => "Mac OS X v10.3", :category_id => "11"},
{:name => "Ultimate", :refname => "Ultimate", :slug => "Ultimate", :category_id => "11"},
{:name => "FreeBSD 2.1.6", :refname => "FreeBSD 2.1.6", :slug => "FreeBSD 2.1.6", :category_id => "11"},
{:name => "FreeBSD 2.2", :refname => "FreeBSD 2.2", :slug => "FreeBSD 2.2", :category_id => "11"},
{:name => "MS/8", :refname => "MS/8", :slug => "MS/8", :category_id => "11"},
{:name => "SOS", :refname => "SOS", :slug => "SOS", :category_id => "11"},
{:name => "Caixa Magica", :refname => "Caixa Magica", :slug => "Caixa Magica", :category_id => "11"},
{:name => "Minerva", :refname => "Minerva", :slug => "Minerva", :category_id => "11"},
{:name => "Asianux", :refname => "Asianux", :slug => "Asianux", :category_id => "11"},
{:name => "Cygwin", :refname => "Cygwin", :slug => "Cygwin", :category_id => "11"},
{:name => "Commodore 64", :refname => "Commodore 64", :slug => "Commodore 64", :category_id => "11"},
{:name => "Google Chrome", :refname => "Google Chrome", :slug => "Google Chrome", :category_id => "11"},
{:name => "Extremely Reliable Operating System", :refname => "Extremely Reliable Operating System", :slug => "Extremely Reliable Operating System", :category_id => "11"},
{:name => "GP32", :refname => "GP32", :slug => "GP32", :category_id => "11"},
{:name => "Windows 3.1x", :refname => "Windows 3.1x", :slug => "Windows 3.1x", :released_at => "1992", :category_id => "11"},
{:name => "Coyotos", :refname => "Coyotos", :slug => "Coyotos", :category_id => "11"},
{:name => "HPBSD", :refname => "HPBSD", :slug => "HPBSD", :category_id => "11"},
{:name => "Mac OS X Lion", :refname => "Mac OS X Lion", :slug => "Mac OS X Lion", :released_at => "2011", :category_id => "11"},
{:name => "CapROS", :refname => "CapROS", :slug => "CapROS", :category_id => "11"},
{:name => "Honeycomb", :refname => "Honeycomb", :slug => "Honeycomb", :released_at => 2011, :category_id => "11"},
{:name => "Dreamlinux", :refname => "Dreamlinux", :slug => "Dreamlinux", :category_id => "11"},
{:name => "Nukernel", :refname => "Nukernel", :slug => "Nukernel", :category_id => "11"},
{:name => "A/UX", :refname => "A/UX", :slug => "A/UX", :category_id => "11"},
{:name => "Solaris Operating System", :refname => "Solaris Operating System", :slug => "Solaris Operating System", :category_id => "11"},
{:name => "Windows Me", :refname => "Windows Me", :slug => "Windows Me", :category_id => "11"},
{:name => "Linux", :refname => "Linux", :slug => "Linux", :category_id => "11"},
{:name => "Plurix", :refname => "Plurix", :slug => "Plurix", :category_id => "11"},
{:name => "Windows Server 2008", :refname => "Windows Server 2008", :slug => "Windows Server 2008", :category_id => "11"},
{:name => "iOS 6", :refname => "iOS 6", :slug => "iOS 6", :released_at => "2012", :category_id => "11"},
{:name => "Corel Linux", :refname => "Corel Linux", :slug => "Corel Linux", :category_id => "11"},
{:name => "FreeBSD 2.2.1", :refname => "FreeBSD 2.2.1", :slug => "FreeBSD 2.2.1", :category_id => "11"},
{:name => "DG/UX", :refname => "DG/UX", :slug => "DG/UX", :category_id => "11"},
{:name => "Frugalware", :refname => "Frugalware", :slug => "Frugalware", :released_at => "2007", :category_id => "11"},
{:name => "Cray Time Sharing System", :refname => "Cray Time Sharing System", :slug => "Cray Time Sharing System", :category_id => "11"},
{:name => "MicroEmpix", :refname => "MicroEmpix", :slug => "MicroEmpix", :category_id => "11"},
{:name => "Softlanding Linux System", :refname => "Softlanding Linux System", :slug => "Softlanding Linux System", :category_id => "11"},
{:name => "U-lite", :refname => "U-lite", :slug => "U-lite", :category_id => "11"},
{:name => "Xenix", :refname => "Xenix", :slug => "Xenix", :category_id => "11"},
{:name => "Zenwalk Linux", :refname => "Zenwalk Linux", :slug => "Zenwalk Linux", :released_at => "2005", :category_id => "11"},
{:name => "JX", :refname => "JX", :slug => "JX", :category_id => "11"},
{:name => "Haiku", :refname => "Haiku", :slug => "Haiku", :category_id => "11"},
{:name => "PC DOS 2.0", :refname => "PC DOS 2.0", :slug => "PC DOS 2.0", :category_id => "11"},
{:name => "Mac OS 7", :refname => "Mac OS 7", :slug => "Mac OS 7", :released_at => "1991", :category_id => "11"},
{:name => "Xinu", :refname => "Xinu", :slug => "Xinu", :category_id => "11"},
{:name => "Sinclair QDOS", :refname => "Sinclair QDOS", :slug => "Sinclair QDOS", :category_id => "11"},
{:name => "Windows Server 2008 Datacenter Edition", :refname => "Windows Server 2008 Datacenter Edition", :slug => "Windows Server 2008 Datacenter Edition", :category_id => "11"},
{:name => "Miraculix", :refname => "Miraculix", :slug => "Miraculix", :category_id => "11"},
{:name => "VeritOS", :refname => "VeritOS", :slug => "VeritOS", :category_id => "11"},
{:name => "OS/2", :refname => "OS/2", :slug => "OS/2", :category_id => "11"},
{:name => "Granular Linux", :refname => "Granular Linux", :slug => "Granular Linux", :category_id => "11"},
{:name => "L3 microkernel", :refname => "L3 microkernel", :slug => "L3 microkernel", :category_id => "11"},
{:name => "Dingoo", :refname => "Dingoo", :slug => "Dingoo", :category_id => "11"},
{:name => "Pinguy OS", :refname => "Pinguy OS", :slug => "Pinguy OS", :category_id => "11"},
{:name => "GNU/Linux", :refname => "GNU/Linux", :slug => "GNU/Linux", :category_id => "11"},
{:name => "SCOPE", :refname => "SCOPE", :slug => "SCOPE", :category_id => "11"},
{:name => "Windows NT 4.0", :refname => "Windows NT 4.0", :slug => "Windows NT 4.0", :released_at => "1996", :category_id => "11"},
{:name => "Windows Vista Home Premium", :refname => "Windows Vista Home Premium", :slug => "Windows Vista Home Premium", :category_id => "11"},
{:name => "Kubuntu 5.10", :refname => "Kubuntu 5.10", :slug => "Kubuntu 5.10", :released_at => "2005", :category_id => "11"},
{:name => "PC DOS 3.3", :refname => "PC DOS 3.3", :slug => "PC DOS 3.3", :category_id => "11"},
{:name => "Oberon operating system", :refname => "Oberon operating system", :slug => "Oberon operating system", :category_id => "11"},
{:name => "Annvix", :refname => "Annvix", :slug => "Annvix", :category_id => "11"},
{:name => "Fermi Linux", :refname => "Fermi Linux", :slug => "Fermi Linux", :category_id => "11"},
{:name => "YOPER", :refname => "YOPER", :slug => "YOPER", :category_id => "11"},
{:name => "KDE Software Compilation", :refname => "KDE Software Compilation", :slug => "KDE Software Compilation", :category_id => "11"},
{:name => "Unix", :refname => "Unix", :slug => "Unix", :category_id => "11"},
{:name => "Linux", :refname => "Linux", :slug => "Linux", :category_id => "11"},
{:name => "ALinux", :refname => "ALinux", :slug => "ALinux", :category_id => "11"},
{:name => "ECos", :refname => "ECos", :slug => "ECos", :category_id => "11"},
{:name => "DragonFly BSD", :refname => "DragonFly BSD", :slug => "DragonFly BSD", :category_id => "11"},
{:name => "GNU/DOS", :refname => "GNU/DOS", :slug => "GNU/DOS", :category_id => "11"},
{:name => "RADIX-50", :refname => "RADIX-50", :slug => "RADIX-50", :category_id => "11"},
{:name => "TinyMe", :refname => "TinyMe", :slug => "TinyMe", :category_id => "11"},
{:name => "GNU/NetBSD", :refname => "GNU/NetBSD", :slug => "GNU/NetBSD", :category_id => "11"},
{:name => "KolibriOS", :refname => "KolibriOS", :slug => "KolibriOS", :category_id => "11"},
{:name => "White Box Enterprise Linux", :refname => "White Box Enterprise Linux", :slug => "White Box Enterprise Linux", :category_id => "11"},
{:name => "Mac OS X v10.0", :refname => "Mac OS X v10.0", :slug => "Mac OS X v10.0", :released_at => "2001", :category_id => "11"},
{:name => "Fedora Core 6", :refname => "Fedora Core 6", :slug => "Fedora Core 6", :category_id => "11"},
{:name => "AROS Research Operating System", :refname => "AROS Research Operating System", :slug => "AROS Research Operating System", :category_id => "11"},
{:name => "VSTa", :refname => "VSTa", :slug => "VSTa", :category_id => "11"},
{:name => "Fedora Core 1", :refname => "Fedora Core 1", :slug => "Fedora Core 1", :category_id => "11"},
{:name => "EmuTOS", :refname => "EmuTOS", :slug => "EmuTOS", :category_id => "11"},
{:name => "TUNIS", :refname => "TUNIS", :slug => "TUNIS", :category_id => "11"},
{:name => "Easy Peasy", :refname => "Easy Peasy", :slug => "Easy Peasy", :category_id => "11"},
{:name => "Phoenix-RTOS", :refname => "Phoenix-RTOS", :slug => "Phoenix-RTOS", :category_id => "11"},
{:name => "SystemRescueCD", :refname => "SystemRescueCD", :slug => "SystemRescueCD", :category_id => "11"},
{:name => "FreeBSD 2.2.5", :refname => "FreeBSD 2.2.5", :slug => "FreeBSD 2.2.5", :category_id => "11"},
{:name => "Mythbuntu", :refname => "Mythbuntu", :slug => "Mythbuntu", :category_id => "11"},
{:name => "OSF/1", :refname => "OSF/1", :slug => "OSF/1", :category_id => "11"},
{:name => "PC DOS 2000", :refname => "PC DOS 2000", :slug => "PC DOS 2000", :category_id => "11"},
{:name => "PC DOS 6.0", :refname => "PC DOS 6.0", :slug => "PC DOS 6.0", :category_id => "11"},
{:name => "Coherent", :refname => "Coherent", :slug => "Coherent", :released_at => "1983", :category_id => "11"},
{:name => "SAM Linux", :refname => "SAM Linux", :slug => "SAM Linux", :category_id => "11"},
{:name => "Mac OS 9", :refname => "Mac OS 9", :slug => "Mac OS 9", :released_at => "1999", :category_id => "11"},
{:name => "IoenOS", :refname => "IoenOS", :slug => "IoenOS", :category_id => "11"},
{:name => "Xubuntu", :refname => "Xubuntu", :slug => "Xubuntu", :category_id => "11"},
{:name => "OpenIndiana", :refname => "OpenIndiana", :slug => "OpenIndiana", :category_id => "11"},
{:name => "Jari OS", :refname => "Jari OS", :slug => "Jari OS", :category_id => "11"},
{:name => "L4 microkernel family", :refname => "L4 microkernel family", :slug => "L4 microkernel family", :category_id => "11"},
{:name => "K42", :refname => "K42", :slug => "K42", :category_id => "11"},
{:name => "OpenBSD", :refname => "OpenBSD", :slug => "OpenBSD", :released_at => "2008", :category_id => "11"},
{:name => "Eumel", :refname => "Eumel", :slug => "Eumel", :category_id => "11"},
{:name => "Windows HPC Server 2008", :refname => "Windows HPC Server 2008", :slug => "Windows HPC Server 2008", :category_id => "11"},
{:name => "Microsoft Windows", :refname => "Microsoft Windows", :slug => "Microsoft Windows", :released_at => "1985", :category_id => "11"},
{:name => "FreeRTOS", :refname => "FreeRTOS", :slug => "FreeRTOS", :category_id => "11"},
{:name => "Windows Vista Home Basic", :refname => "Windows Vista Home Basic", :slug => "Windows Vista Home Basic", :category_id => "11"},
{:name => "Debian GNU/Linux", :refname => "Debian GNU/Linux", :slug => "Debian GNU/Linux", :released_at => "1993", :category_id => "11"},
{:name => "GNU", :refname => "GNU", :slug => "GNU", :category_id => "11"},
{:name => "SMSQ/E", :refname => "SMSQ/E", :slug => "SMSQ/E", :category_id => "11"},
{:name => "FreeVMS", :refname => "FreeVMS", :slug => "FreeVMS", :category_id => "11"},
{:name => "Qtopia", :refname => "Qtopia", :slug => "Qtopia", :category_id => "11"},
{:name => "Z-DOS", :refname => "Z-DOS", :slug => "Z-DOS", :category_id => "11"},
{:name => "PSOS", :refname => "PSOS", :slug => "PSOS", :released_at => "1982", :category_id => "11"},
{:name => "Vine Linux", :refname => "Vine Linux", :slug => "Vine Linux", :category_id => "11"},
{:name => "MS-DOS 5.0", :refname => "MS-DOS 5.0", :slug => "MS-DOS 5.0", :released_at => "1991", :category_id => "11"},
{:name => "Sirius RTOS", :refname => "Sirius RTOS", :slug => "Sirius RTOS", :category_id => "11"},
{:name => "DOS Plus", :refname => "DOS Plus", :slug => "DOS Plus", :category_id => "11"},
{:name => "Dex4u", :refname => "Dex4u", :slug => "Dex4u", :category_id => "11"},
{:name => "WPS-8", :refname => "WPS-8", :slug => "WPS-8", :category_id => "11"},
{:name => "Z/OS", :refname => "Z/OS", :slug => "Z/OS", :category_id => "11"},
{:name => "INTERACTIVE UNIX", :refname => "INTERACTIVE UNIX", :slug => "INTERACTIVE UNIX", :category_id => "11"},
{:name => "Ice Cream Sandwich", :refname => "Ice Cream Sandwich", :slug => "Ice Cream Sandwich", :released_at => "2011", :category_id => "11"},
{:name => "FreeBSD 2.0", :refname => "FreeBSD 2.0", :slug => "FreeBSD 2.0", :category_id => "11"},
{:name => "4.3BSD NET/2", :refname => "4.3BSD NET/2", :slug => "4.3BSD NET/2", :category_id => "11"},
{:name => "Sprite operating system", :refname => "Sprite operating system", :slug => "Sprite operating system", :category_id => "11"},
{:name => "Fedora", :refname => "Fedora", :slug => "Fedora", :category_id => "11"},
{:name => "Game Boy Advance", :refname => "Game Boy Advance", :slug => "Game Boy Advance", :category_id => "11"},
{:name => "IRIX", :refname => "IRIX", :slug => "IRIX", :category_id => "11"},
{:name => "SUSE Linux Enterprise Desktop", :refname => "SUSE Linux Enterprise Desktop", :slug => "SUSE Linux Enterprise Desktop", :category_id => "11"},
{:name => "Sidux", :refname => "Sidux", :slug => "Sidux", :category_id => "11"},
{:name => "Berry Linux", :refname => "Berry Linux", :slug => "Berry Linux", :category_id => "11"},
{:name => "DOS/BATCH 11", :refname => "DOS/BATCH 11", :slug => "DOS/BATCH 11", :category_id => "11"},
{:name => "MSX-DOS", :refname => "MSX-DOS", :slug => "MSX-DOS", :category_id => "11"},
{:name => "Hydra", :refname => "Hydra", :slug => "Hydra", :category_id => "11"},
{:name => "Autocad", :refname => "Autocad", :slug => "Autocad", :category_id => "11"},
{:name => "linuX-gamers", :refname => "linuX-gamers", :slug => "linuX-gamers", :category_id => "11"},
{:name => "Kubuntu 7.10", :refname => "Kubuntu 7.10", :slug => "Kubuntu 7.10", :released_at => "2007", :category_id => "11"},
{:name => "Pilot", :refname => "Pilot", :slug => "Pilot", :released_at => "1977", :category_id => "11"},
{:name => "BackTrack", :refname => "BackTrack", :slug => "BackTrack", :category_id => "11"},
{:name => "Symbian", :refname => "Symbian", :slug => "Symbian", :category_id => "11"},
{:name => "Atari TOS", :refname => "Atari TOS", :slug => "Atari TOS", :category_id => "11"},
{:name => "Co-CreateLinux", :refname => "Co-CreateLinux", :slug => "Co-CreateLinux", :category_id => "11"},
{:name => "EnterpriseBSD", :refname => "EnterpriseBSD", :slug => "EnterpriseBSD", :category_id => "11"},
{:name => "Derrick Operating System", :refname => "Derrick Operating System", :slug => "Derrick Operating System", :category_id => "11"},
{:name => "POSIX", :refname => "POSIX", :slug => "POSIX", :category_id => "11"},
{:name => "Mac OS X Mountain Lion", :refname => "Mac OS X Mountain Lion", :slug => "Mac OS X Mountain Lion", :released_at => "2012", :category_id => "11"},
{:name => "DOS XL", :refname => "DOS XL", :slug => "DOS XL", :category_id => "11"},
{:name => "Disk Extended Color Basic", :refname => "Disk Extended Color Basic", :slug => "Disk Extended Color Basic", :category_id => "11"},
{:name => "Moblin", :refname => "Moblin", :slug => "Moblin", :category_id => "11"},
{:name => "Cosmos", :refname => "Cosmos", :slug => "Cosmos", :category_id => "11"},
{:name => "SINIX", :refname => "SINIX", :slug => "SINIX", :category_id => "11"},
{:name => "SUSE Linux", :refname => "SUSE Linux", :slug => "SUSE Linux", :released_at => "2006", :category_id => "11"},
{:name => "ITRON Project", :refname => "ITRON Project", :slug => "ITRON Project", :category_id => "11"},
{:name => "OpenSUSE", :refname => "OpenSUSE", :slug => "OpenSUSE", :category_id => "11"},
{:name => "FreeBSD 2.2.2", :refname => "FreeBSD 2.2.2", :slug => "FreeBSD 2.2.2", :category_id => "11"},
{:name => "CSI-DOS", :refname => "CSI-DOS", :slug => "CSI-DOS", :category_id => "11"},
{:name => "PTS-DOS", :refname => "PTS-DOS", :slug => "PTS-DOS", :category_id => "11"},
{:name => "Hikarunix", :refname => "Hikarunix", :slug => "Hikarunix", :category_id => "11"},
{:name => "Windows Small Business Server 2008", :refname => "Windows Small Business Server 2008", :slug => "Windows Small Business Server 2008", :category_id => "11"},
{:name => "Windows Essential Business Server 2008", :refname => "Windows Essential Business Server 2008", :slug => "Windows Essential Business Server 2008", :category_id => "11"},
{:name => "BeRTOS", :refname => "BeRTOS", :slug => "BeRTOS", :category_id => "11"},
{:name => "Jelly Bean", :refname => "Jelly Bean", :slug => "Jelly Bean", :category_id => "11"},
{:name => "Palm OS", :refname => "Palm OS", :slug => "Palm OS", :category_id => "11"},
{:name => "TI89", :refname => "TI89", :slug => "TI89", :category_id => "11"},
{:name => "XrossMediaBar", :refname => "XrossMediaBar", :slug => "XrossMediaBar", :category_id => "11"},
{:name => "Android", :refname => "Android", :slug => "Android", :released_at => "2008", :category_id => "11"},
{:name => "V", :refname => "V", :slug => "V", :category_id => "11"},
{:name => "FreeBSD", :refname => "FreeBSD", :slug => "FreeBSD", :category_id => "11"},
{:name => "OZONE", :refname => "OZONE", :slug => "OZONE", :category_id => "11"},
{:name => "Vida Linux", :refname => "Vida Linux", :slug => "Vida Linux", :category_id => "11"},
{:name => "Windows XP 64-bit Edition", :refname => "Windows XP 64-bit Edition", :slug => "Windows XP 64-bit Edition", :category_id => "11"},
{:name => "VM/CMS", :refname => "VM/CMS", :slug => "VM/CMS", :category_id => "11"},
{:name => "Junos", :refname => "Junos", :slug => "Junos", :category_id => "11"},
{:name => "NEXTSTEP", :refname => "NEXTSTEP", :slug => "NEXTSTEP", :category_id => "11"},
{:name => "DEMOS", :refname => "DEMOS", :slug => "DEMOS", :category_id => "11"},
{:name => "Windows 2000 Advanced Server Limited Edition", :refname => "Windows 2000 Advanced Server Limited Edition", :slug => "Windows 2000 Advanced Server Limited Edition", :category_id => "11"},
{:name => "PC DOS 5.0", :refname => "PC DOS 5.0", :slug => "PC DOS 5.0", :category_id => "11"},
{:name => "Windows 2000 Server", :refname => "Windows 2000 Server", :slug => "Windows 2000 Server", :category_id => "11"},
{:name => "Windows Server", :refname => "Windows Server", :slug => "Windows Server", :category_id => "11"},
{:name => "TRS-DOS", :refname => "TRS-DOS", :slug => "TRS-DOS", :category_id => "11"},
{:name => "PlayStation", :refname => "PlayStation", :slug => "PlayStation", :category_id => "11"},
{:name => "OS-9", :refname => "OS-9", :slug => "OS-9", :category_id => "11"},
{:name => "Kubuntu 6.10", :refname => "Kubuntu 6.10", :slug => "Kubuntu 6.10", :released_at => "2006", :category_id => "11"},
{:name => "Linpus Linux", :refname => "Linpus Linux", :slug => "Linpus Linux", :category_id => "11"},
{:name => "DC/OSx", :refname => "DC/OSx", :slug => "DC/OSx", :category_id => "11"},
{:name => "Es", :refname => "Es", :slug => "Es", :category_id => "11"},
{:name => "Nintendo DS", :refname => "Nintendo DS", :slug => "Nintendo DS", :category_id => "11"},
{:name => "Amiga Unix", :refname => "Amiga Unix", :slug => "Amiga Unix", :category_id => "11"},
{:name => "Commodore BASIC", :refname => "Commodore BASIC", :slug => "Commodore BASIC", :category_id => "11"},
{:name => "Prex", :refname => "Prex", :slug => "Prex", :category_id => "11"},
{:name => "SunOS", :refname => "SunOS", :slug => "SunOS", :category_id => "11"},
{:name => "Darwin", :refname => "Darwin", :slug => "Darwin", :category_id => "11"},
{:name => "Tinfoil Hat Linux", :refname => "Tinfoil Hat Linux", :slug => "Tinfoil Hat Linux", :category_id => "11"},
{:name => "Freespire", :refname => "Freespire", :slug => "Freespire", :category_id => "11"},
{:name => "Fedora Core 4", :refname => "Fedora Core 4", :slug => "Fedora Core 4", :category_id => "11"},
{:name => "DSPnano RTOS", :refname => "DSPnano RTOS", :slug => "DSPnano RTOS", :category_id => "11"},
{:name => "NewDos/80", :refname => "NewDos/80", :slug => "NewDos/80", :category_id => "11"},
{:name => "Java Platform, Micro Edition", :refname => "Java Platform, Micro Edition", :slug => "Java Platform, Micro Edition", :category_id => "11"},
{:name => "OS/400", :refname => "OS/400", :slug => "OS/400", :released_at => "2006", :category_id => "11"},
{:name => "MorphOS", :refname => "MorphOS", :slug => "MorphOS", :category_id => "11"},
{:name => "MS-DOS 3.0", :refname => "MS-DOS 3.0", :slug => "MS-DOS 3.0", :released_at => "1984", :category_id => "11"},
{:name => "MS-DOS 8.0", :refname => "MS-DOS 8.0", :slug => "MS-DOS 8.0", :released_at => "2000", :category_id => "11"},
{:name => "Kubuntu 10.10", :refname => "Kubuntu 10.10", :slug => "Kubuntu 10.10", :category_id => "11"},
{:name => "VPS/VM", :refname => "VPS/VM", :slug => "VPS/VM", :category_id => "11"},
{:name => "Quark", :refname => "Quark", :slug => "Quark", :category_id => "11"},
{:name => "FreeBSD 2.x", :refname => "FreeBSD 2.x", :slug => "FreeBSD 2.x", :category_id => "11"},
{:name => "MNOS", :refname => "MNOS", :slug => "MNOS", :category_id => "11"},
{:name => "Kubuntu 8.10", :refname => "Kubuntu 8.10", :slug => "Kubuntu 8.10", :released_at => "2008", :category_id => "11"},
{:name => "HDOS", :refname => "HDOS", :slug => "HDOS", :category_id => "11"},
{:name => "Linux Mint", :refname => "Linux Mint", :slug => "Linux Mint", :category_id => "11"},
{:name => "Test OS", :refname => "Test OS", :slug => "Test OS", :category_id => "11"},
{:name => "Mac OS X v10.5", :refname => "Mac OS X v10.5", :slug => "Mac OS X v10.5", :released_at => "2007", :category_id => "11"},
{:name => "Kubuntu 8.04", :refname => "Kubuntu 8.04", :slug => "Kubuntu 8.04", :released_at => "2008", :category_id => "11"},
{:name => "SUSE Linux distributions", :refname => "SUSE Linux distributions", :slug => "SUSE Linux distributions", :category_id => "11"},
{:name => "Symbian OS 9.1", :refname => "Symbian OS 9.1", :slug => "Symbian OS 9.1", :category_id => "11"},
{:name => "Windows XP Home Edition", :refname => "Windows XP Home Edition", :slug => "Windows XP Home Edition", :category_id => "11"},
{:name => "Windows Mobile Standard", :refname => "Windows Mobile Standard", :slug => "Windows Mobile Standard", :category_id => "11"},
{:name => "Psion 3", :refname => "Psion 3", :slug => "Psion 3", :category_id => "11"},
{:name => "System File", :refname => "System File", :slug => "System File", :category_id => "11"},
{:name => "Interix", :refname => "Interix", :slug => "Interix", :category_id => "11"},
{:name => "Bluebottle OS", :refname => "Bluebottle OS", :slug => "Bluebottle OS", :category_id => "11"},
{:name => "MS-DOS", :refname => "MS-DOS", :slug => "MS-DOS", :released_at => "1981", :category_id => "11"},
{:name => "CP-V", :refname => "CP-V", :slug => "CP-V", :category_id => "11"},
{:name => "Venix", :refname => "Venix", :slug => "Venix", :category_id => "11"},
{:name => "Ubuntu 10.04", :refname => "Ubuntu 10.04", :slug => "Ubuntu 10.04", :released_at => "2010", :category_id => "11"},
{:name => "RT-11", :refname => "RT-11", :slug => "RT-11", :category_id => "11"},
{:name => "Windows Server 2008 Standard Edition", :refname => "Windows Server 2008 Standard Edition", :slug => "Windows Server 2008 Standard Edition", :category_id => "11"},
{:name => "Banyan VINES", :refname => "Banyan VINES", :slug => "Banyan VINES", :category_id => "11"},
{:name => "Safari", :refname => "Safari", :slug => "Safari", :category_id => "11"},
{:name => "Novell NetWare", :refname => "Novell NetWare", :slug => "Novell NetWare", :category_id => "11"},
{:name => "Pardus", :refname => "Pardus", :slug => "Pardus", :category_id => "11"},
{:name => "Windows 1.0", :refname => "Windows 1.0", :slug => "Windows 1.0", :category_id => "11"},
{:name => "Amstrad CPC", :refname => "Amstrad CPC", :slug => "Amstrad CPC", :category_id => "11"},
{:name => "iOS", :refname => "iOS", :slug => "iOS", :released_at => "2007", :category_id => "11"},
{:name => "MINIX 3", :refname => "MINIX 3", :slug => "MINIX 3", :category_id => "11"},
{:name => "Windows 2000", :refname => "Windows 2000", :slug => "Windows 2000", :released_at => "2000", :category_id => "11"},
{:name => "IX", :refname => "IX", :slug => "IX", :category_id => "11"},
{:name => "Firefly BSD", :refname => "Firefly BSD", :slug => "Firefly BSD", :category_id => "11"},
{:name => "Lubuntu", :refname => "Lubuntu", :slug => "Lubuntu", :category_id => "11"},
{:name => "Singularity", :refname => "Singularity", :slug => "Singularity", :category_id => "11"},
{:name => "FreeBSD 1.0", :refname => "FreeBSD 1.0", :slug => "FreeBSD 1.0", :category_id => "11"},
{:name => "TRAX", :refname => "TRAX", :slug => "TRAX", :category_id => "11"},
{:name => "Commodore DOS", :refname => "Commodore DOS", :slug => "Commodore DOS", :category_id => "11"},
{:name => "ALT Linux", :refname => "ALT Linux", :slug => "ALT Linux", :category_id => "11"},
{:name => "CP/M", :refname => "CP/M", :slug => "CP/M", :category_id => "11"},
{:name => "MenuetOS", :refname => "MenuetOS", :slug => "MenuetOS", :category_id => "11"},
{:name => "CatOS", :refname => "CatOS", :slug => "CatOS", :category_id => "11"},
{:name => "PlayStation Portable", :refname => "PlayStation Portable", :slug => "PlayStation Portable", :category_id => "11"},
{:name => "FreeBSD 1.1.5.1", :refname => "FreeBSD 1.1.5.1", :slug => "FreeBSD 1.1.5.1", :category_id => "11"},
{:name => "GeckOS", :refname => "GeckOS", :slug => "GeckOS", :category_id => "11"},
{:name => "Opera", :refname => "Opera", :slug => "Opera", :category_id => "11"},
{:name => "Nokia N800", :refname => "Nokia N800", :slug => "Nokia N800", :category_id => "11"},
{:name => "Arch Linux", :refname => "Arch Linux", :slug => "Arch Linux", :category_id => "11"},
{:name => "Windows Phone 7", :refname => "Windows Phone 7", :slug => "Windows Phone 7", :category_id => "11"},
{:name => "FreeDOS", :refname => "FreeDOS", :slug => "FreeDOS", :category_id => "11"},
{:name => "Scientific Linux", :refname => "Scientific Linux", :slug => "Scientific Linux", :category_id => "11"},
{:name => "Red Flag Linux", :refname => "Red Flag Linux", :slug => "Red Flag Linux", :category_id => "11"},
{:name => "House", :refname => "House", :slug => "House", :category_id => "11"},
{:name => "CentOS", :refname => "CentOS", :slug => "CentOS", :released_at => "2007", :category_id => "11"},
{:name => "OpenGEU", :refname => "OpenGEU", :slug => "OpenGEU", :category_id => "11"},
{:name => "LoseThos", :refname => "LoseThos", :slug => "LoseThos", :category_id => "11"},
{:name => "Ensemble", :refname => "Ensemble", :slug => "Ensemble", :category_id => "11"},
{:name => "Ubuntu 11.10", :refname => "Ubuntu 11.10", :slug => "Ubuntu 11.10", :released_at => "2011", :category_id => "11"},
{:name => "Transaction Processing Facility", :refname => "Transaction Processing Facility", :slug => "Transaction Processing Facility", :category_id => "11"},
{:name => "OpenSolaris", :refname => "OpenSolaris", :slug => "OpenSolaris", :category_id => "11"},
{:name => "MiNT", :refname => "MiNT", :slug => "MiNT", :category_id => "11"},
{:name => "Knoppix", :refname => "Knoppix", :slug => "Knoppix", :released_at => "2007", :category_id => "11"},
{:name => "Kubuntu 10.04", :refname => "Kubuntu 10.04", :slug => "Kubuntu 10.04", :category_id => "11"},
{:name => "BTRON", :refname => "BTRON", :slug => "BTRON", :category_id => "11"},
{:name => "RSTS/E", :refname => "RSTS/E", :slug => "RSTS/E", :category_id => "11"},
{:name => "EXEC 8", :refname => "EXEC 8", :slug => "EXEC 8", :released_at => 1964, :category_id => "11"},
{:name => "CTRON", :refname => "CTRON", :slug => "CTRON", :category_id => "11"},
{:name => "Domain/OS", :refname => "Domain/OS", :slug => "Domain/OS", :category_id => "11"},
{:name => "GEOS", :refname => "GEOS", :slug => "GEOS", :category_id => "11"},
{:name => "NetBSD", :refname => "NetBSD", :slug => "NetBSD", :category_id => "11"},
{:name => "Windows XP Media Center Edition", :refname => "Windows XP Media Center Edition", :slug => "Windows XP Media Center Edition", :category_id => "11"},
{:name => "CP/M-86", :refname => "CP/M-86", :slug => "CP/M-86", :category_id => "11"},
{:name => "SHARE Operating System", :refname => "SHARE Operating System", :slug => "SHARE Operating System", :category_id => "11"},
{:name => "USIX", :refname => "USIX", :slug => "USIX", :category_id => "11"},
{:name => "HelenOS", :refname => "HelenOS", :slug => "HelenOS", :category_id => "11"},
{:name => "all", :refname => "all", :slug => "all", :category_id => "11"},
{:name => "Sanos", :refname => "Sanos", :slug => "Sanos", :category_id => "11"},
{:name => "PC DOS 4.0", :refname => "PC DOS 4.0", :slug => "PC DOS 4.0", :category_id => "11"},
{:name => "Windows CE", :refname => "Windows CE", :slug => "Windows CE", :category_id => "11"},
{:name => "Windows 2000 Professional", :refname => "Windows 2000 Professional", :slug => "Windows 2000 Professional", :category_id => "11"},
{:name => "MeeGo", :refname => "MeeGo", :slug => "MeeGo", :released_at => "2010", :category_id => "11"},
{:name => "M-DOS", :refname => "M-DOS", :slug => "M-DOS", :category_id => "11"},
{:name => "Kurumin Linux", :refname => "Kurumin Linux", :slug => "Kurumin Linux", :category_id => "11"},
{:name => "Puppy Linux", :refname => "Puppy Linux", :slug => "Puppy Linux", :category_id => "11"},
{:name => "Hivemind", :refname => "Hivemind", :slug => "Hivemind", :category_id => "11"},
{:name => "UniFlex", :refname => "UniFlex", :slug => "UniFlex", :category_id => "11"},
{:name => "BLAG Linux and GNU", :refname => "BLAG Linux and GNU", :slug => "BLAG Linux and GNU", :category_id => "11"},
{:name => "Windows 95", :refname => "Windows 95", :slug => "Windows 95", :released_at => "1995", :category_id => "11"},
{:name => "MS-DOS 6.0", :refname => "MS-DOS 6.0", :slug => "MS-DOS 6.0", :released_at => "1993", :category_id => "11"},
{:name => "MS-DOS 1.25", :refname => "MS-DOS 1.25", :slug => "MS-DOS 1.25", :released_at => "1982", :category_id => "11"},
{:name => "MythDora", :refname => "MythDora", :slug => "MythDora", :category_id => "11"},
{:name => "Mac OS X v10.4", :refname => "Mac OS X v10.4", :slug => "Mac OS X v10.4", :released_at => "2005", :category_id => "11"},
{:name => "VAXELN", :refname => "VAXELN", :slug => "VAXELN", :category_id => "11"},
{:name => "Windows 2.0", :refname => "Windows 2.0", :slug => "Windows 2.0", :category_id => "11"},
{:name => "AtheOS", :refname => "AtheOS", :slug => "AtheOS", :category_id => "11"},
{:name => "Integer BASIC", :refname => "Integer BASIC", :slug => "Integer BASIC", :category_id => "11"},
{:name => "Windows XP Professional", :refname => "Windows XP Professional", :slug => "Windows XP Professional", :category_id => "11"},
{:name => "Windows Mobile Smartphone", :refname => "Windows Mobile Smartphone", :slug => "Windows Mobile Smartphone", :category_id => "11"},
{:name => "Windows Vista Enterprise", :refname => "Windows Vista Enterprise", :slug => "Windows Vista Enterprise", :category_id => "11"},
{:name => "FutureOS", :refname => "FutureOS", :slug => "FutureOS", :category_id => "11"},
{:name => "gOS", :refname => "gOS", :slug => "gOS", :category_id => "11"},
{:name => "BlackBerry", :refname => "BlackBerry", :slug => "BlackBerry", :released_at => 1997, :category_id => "11"},
{:name => "Midori", :refname => "Midori", :slug => "Midori", :category_id => "11"},
{:name => "RBM-1", :refname => "RBM-1", :slug => "RBM-1", :category_id => "11"},
{:name => "Acorn MOS", :refname => "Acorn MOS", :slug => "Acorn MOS", :category_id => "11"},
{:name => "Openmamba", :refname => "Openmamba", :slug => "Openmamba", :category_id => "11"},
{:name => "Mac OS 8", :refname => "Mac OS 8", :slug => "Mac OS 8", :released_at => "1997", :category_id => "11"},
{:name => "Psion 5", :refname => "Psion 5", :slug => "Psion 5", :category_id => "11"},
{:name => "PS2 Linux", :refname => "PS2 Linux", :slug => "PS2 Linux", :category_id => "11"},
{:name => "RISC/os", :refname => "RISC/os", :slug => "RISC/os", :category_id => "11"},
{:name => "GNU Mach", :refname => "GNU Mach", :slug => "GNU Mach", :category_id => "11"},
{:name => "Nemesis", :refname => "Nemesis", :slug => "Nemesis", :category_id => "11"},
{:name => "Minix-vmd", :refname => "Minix-vmd", :slug => "Minix-vmd", :category_id => "11"},
{:name => "MeikOS", :refname => "MeikOS", :slug => "MeikOS", :category_id => "11"},
{:name => "BlackBerry Tablet OS", :refname => "BlackBerry Tablet OS", :slug => "BlackBerry Tablet OS", :category_id => "11"},
{:name => "GNU Hurd", :refname => "GNU Hurd", :slug => "GNU Hurd", :category_id => "11"},
{:name => "TOPS-10", :refname => "TOPS-10", :slug => "TOPS-10", :category_id => "11"},
{:name => "Soft Hard Real-Time Kernel", :refname => "Soft Hard Real-Time Kernel", :slug => "Soft Hard Real-Time Kernel", :category_id => "11"},
{:name => "FreeBSD 1.x", :refname => "FreeBSD 1.x", :slug => "FreeBSD 1.x", :category_id => "11"},
{:name => "IBM AIX", :refname => "IBM AIX", :slug => "IBM AIX", :released_at => 1986, :category_id => "11"}]



################################################################################################
################################################################################################
##########                            Web Browsers Data                          ###############
################################################################################################
################################################################################################


#Seeding Web Browsers
Product.create [{:name => "Google Chrome OS", :slug => "Google Chrome OS", :category_id => "13"},
                {:name => "Flock", :slug => "Flock", :category_id => "13"},
                {:name => "Netscape", :slug => "Netscape", :category_id => "13"},
                {:name => "Dillo", :slug => "Dillo", :category_id => "13"},
                {:name => "SPIN", :slug => "SPIN", :category_id => "13"},
                {:name => "Oregano", :slug => "Oregano", :category_id => "13"},
                {:name => "Internet Explorer 9", :slug => "Internet Explorer 9", :category_id => "13"},
                {:name => "Arachne", :slug => "Arachne", :category_id => "13"},
                {:name => "Internet Explorer for Mac", :slug => "Internet Explorer for Mac", :category_id => "13"},
                {:name => "RockMelt", :slug => "RockMelt", :category_id => "13"},
                {:name => "Uzbl", :slug => "Uzbl", :category_id => "13"},
                {:name => "Netscape Browser", :slug => "Netscape Browser", :category_id => "13"},
                {:name => "Arora", :slug => "Arora", :category_id => "13"},
                {:name => "Arena", :slug => "Arena", :category_id => "13"},
                {:name => "Charon", :slug => "Charon", :category_id => "13"},
                {:name => "PlayStation Portable web browser", :slug => "PlayStation Portable web browser", :category_id => "13"},
                {:name => "Mozilla Firefox", :slug => "Mozilla Firefox", :category_id => "13"},
                {:name => "Google Chrome", :slug => "Google Chrome", :category_id => "13"},
                {:name => "SlipKnot", :slug => "SlipKnot", :category_id => "13"},
                {:name => "ICab", :slug => "ICab", :category_id => "13"},
                {:name => "Swift", :slug => "Swift", :category_id => "13"},
                {:name => "Netscape Navigator", :slug => "Netscape Navigator", :category_id => "13"},
                {:name => "Salamander", :slug => "Salamander", :category_id => "13"},
                {:name => "Internet Explorer", :slug => "Internet Explorer", :category_id => "13"},
                {:name => "Abaco", :slug => "Abaco", :category_id => "13"},
                {:name => "surf", :slug => "surf", :category_id => "13"},
                {:name => "Voyager", :slug => "Voyager", :category_id => "13"},
                {:name => "Yahoo Axis", :slug => "Yahoo Axis", :category_id => "13"},
                {:name => "Konqueror", :slug => "Konqueror", :category_id => "13"},
                {:name => "Netscape Communicator", :slug => "Netscape Communicator", :category_id => "13"},
                {:name => "Midori", :slug => "Midori", :category_id => "13"},
                {:name => "Web Browser for S60", :slug => "Web Browser for S60", :category_id => "13"},
                {:name => "Opera Mobile", :slug => "Opera Mobile", :category_id => "13"},
                {:name => "Mosaic", :slug => "Mosaic", :category_id => "13"},
                {:name => "Wii Browser", :slug => "Wii Browser", :category_id => "13"},
                {:name => "luakit", :slug => "luakit", :category_id => "13"},
                {:name => "jumanji", :slug => "jumanji", :category_id => "13"},
                {:name => "3B", :slug => "3B", :category_id => "13"},
                {:name => "Mothra", :slug => "Mothra", :category_id => "13"},
                {:name => "SeaMonkey", :slug => "SeaMonkey", :category_id => "13"},
                {:name => "Links", :slug => "Links", :category_id => "13"},
                {:name => "Chromium", :slug => "Chromium", :category_id => "13"},
                {:name => "Camino", :slug => "Camino", :category_id => "13"},
                {:name => "Cello", :slug => "Cello", :category_id => "13"},
                {:name => "Conkeror", :slug => "Conkeror", :category_id => "13"},
                {:name => "Ozone", :slug => "Ozone", :category_id => "13"},
                {:name => "Konqueror Embedded", :slug => "Konqueror Embedded", :category_id => "13"},
                {:name => "Epiphany", :slug => "Epiphany", :category_id => "13"},
                {:name => "Grail", :slug => "Grail", :category_id => "13"},
                {:name => "Internet Explorer 8", :slug => "Internet Explorer 8", :category_id => "13"},
                {:name => "Sleipnir", :slug => "Sleipnir", :category_id => "13"},
                {:name => "Lynx", :slug => "Lynx", :category_id => "13"},
                {:name => "NetFront", :slug => "NetFront", :category_id => "13"},
                {:name => "Amaya", :slug => "Amaya", :category_id => "13"},
                {:name => "Opera", :slug => "Opera", :category_id => "13"},
                {:name => "Safari", :slug => "Safari", :category_id => "13"},
                {:name => "Shiira", :slug => "Shiira", :category_id => "13"},
                {:name => "Opera Mini", :slug => "Opera Mini", :category_id => "13"},
                {:name => "Avant Browser", :slug => "Avant Browser", :category_id => "13"},
                {:name => "Blazer", :slug => "Blazer", :category_id => "13"}]



################################################################################################
################################################################################################
##########                     Programming Languages Data                        ###############
################################################################################################
################################################################################################


