# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

################################################################################################
################################################################################################
##########                              Parallel Data                            ###############
################################################################################################
################################################################################################


#Seeding categories #11 element
Category.create [{:name => 'Hightech', :slug => 'hightech', :parent_id => '0'}, #1

                 {:name => 'Phones', :slug => 'phones', :parent_id => '1'}, #2
                 {:name => 'Tablets', :slug => 'tablets', :parent_id => '1'},
                 {:name => 'Cameras', :slug => 'cameras', :parent_id => '1'}, #4
                 {:name => 'Computers', :slug => 'computers', :parent_id => '1'},
                 {:name => 'Consoles', :slug => 'consoles', :parent_id => '1'}, #6


                 {:name => 'Softwares', :slug => 'softwares', :parent_id => '0'},

                 {:name => 'Video Games', :slug => 'video-games', :parent_id => '7'}, #8
                 {:name => 'Programming Languages', :slug => 'programming-languages', :parent_id => '7'},
                 {:name => 'Programming Frameworks', :slug => 'programming-frameworks', :parent_id => '7'}, #10
                 {:name => 'Operating Systems', :slug => 'operating-systems', :parent_id => '7'},
                 {:name => 'Webhosting', :slug => 'webhosting', :parent_id => '7'}, #12
                 {:name => 'Web Browsers', :slug => 'webbrowsers', :parent_id => '7'},



                 {:name => 'Travel and Lifestyle', :slug => 'travel-and-lifestyle', :parent_id => '0'}, #14

                 {:name => 'Hotels', :slug => 'hotels', :parent_id => '14'},
                 {:name => 'Travel Agencies', :slug => 'travel-agencies', :parent_id => '14'}, #16
                 {:name => 'Destinations', :slug => 'destinations', :parent_id => '14'},
                 {:name => 'Airlines', :slug => 'airlines', :parent_id => '14'}, #18


                 {:name => 'Motors', :slug => "motors", :parent_id => '0'},

                 {:name => 'Cars', :slug => 'cars', :parent_id => '19'}, #20
                 {:name => 'Boats', :slug => 'boats', :parent_id => '19'},
                 {:name => 'Motorcycles', :slug => 'Motorcycles', :parent_id => '19'}, #22
                 {:name => 'Car Insurances', :slug => 'car-insurances', :parent_id => '19'},
                 {:name => 'Tractors', :slug => 'tractors', :parent_id => '19'}, #24
                 {:name => 'Engines', :slug => 'Engines', :parent_id => '19'}]


#seeding continents
Continent.create [{:name => 'Africa'},
                  {:name => 'Antarctica'},
                  {:name => 'Asia'},
                  {:name => 'Australia'},
                  {:name => 'Europe'},
                  {:name => 'North America'},
                  {:name => 'South America'}]

#Seeding countries
Country.create [{:name => 'Andorra', :continent_id => 5},
                {:name => 'United Arab Emirates', :continent_id => 3},
                {:name => 'Afghanistan', :continent_id => 3},
                {:name => 'Antigua and Barbuda', :continent_id => 7},
                {:name => 'Anguilla', :continent_id => 1},
                {:name => 'Albania', :continent_id => 5},
                {:name => 'Armenia', :continent_id => 3},
                {:name => 'Netherlands Antilles', :continent_id => 5},
                {:name => 'Angola', :continent_id => 1},
                {:name => 'Antarctica', :continent_id => 5},
                {:name => 'Argentina', :continent_id => 7},
                {:name => 'American Samoa', :continent_id => 4},
                {:name => 'Austria', :continent_id => 5},
                {:name => 'Australia', :continent_id => 4},
                {:name => 'Aruba', :continent_id => 6},
                {:name => 'Aland Islands', :continent_id => 5},
                {:name => 'Azerbaijan', :continent_id => 3},
                {:name => 'Bosnia and Herzegovina', :continent_id => 5},
                {:name => 'Barbados', :continent_id => 7},
                {:name => 'Bangladesh', :continent_id => 3},
                {:name => 'Belgium', :continent_id => 5},
                {:name => 'Burkina Faso', :continent_id => 1},
                {:name => 'Bulgaria', :continent_id => 5},
                {:name => 'Bahrain', :continent_id => 3},
                {:name => 'Burundi', :continent_id => 1},
                {:name => 'Benin', :continent_id => 1},
                {:name => 'Saint Barthelemy', :continent_id => 7},
                {:name => 'Bermuda', :continent_id => 6},
                {:name => 'Brunei', :continent_id => 3},
                {:name => 'Bolivia', :continent_id => 7},
                {:name => 'British Antarctic Territory', :continent_id => 2},
                {:name => 'Brazil', :continent_id => 7},
                {:name => 'Bahamas', :continent_id => 7},
                {:name => 'Bhutan', :continent_id => 3},
                {:name => 'Bouvet Island', :continent_id => 2},
                {:name => 'Botswana', :continent_id => 1},
                {:name => 'Belarus', :continent_id => 5},
                {:name => 'Belize', :continent_id => 7},
                {:name => 'Canada', :continent_id => 6},
                {:name => 'Cocos [Keeling] Islands', :continent_id => 3},
                {:name => 'Congo - Kinshasa', :continent_id => 1},
                {:name => 'Central African Republic', :continent_id => 1},
                {:name => 'Congo - Brazzaville', :continent_id => 1},
                {:name => 'Switzerland', :continent_id => 5},
                {:name => 'Cote d\'Ivoire', :continent_id => 1},
                {:name => 'Cook Islands', :continent_id => 4},
                {:name => 'Chile', :continent_id => 7},
                {:name => 'Cameroon', :continent_id => 1},
                {:name => 'China', :continent_id => 3},
                {:name => 'Colombia', :continent_id => 7},
                {:name => 'Costa Rica', :continent_id => 7},
                {:name => 'Serbia and Montenegro', :continent_id => 5},
                {:name => 'Canton and Enderbury Islands', :continent_id => 3},
                {:name => 'Cuba', :continent_id => 7},
                {:name => 'Cape Verde', :continent_id => 1},
                {:name => 'Christmas Island', :continent_id => 4},
                {:name => 'Cyprus', :continent_id => 5},
                {:name => 'Czech Republic', :continent_id => 5},
                {:name => 'East Germany', :continent_id => 5},
                {:name => 'Germany', :continent_id => 5},
                {:name => 'Djibouti', :continent_id => 1},
                {:name => 'Denmark', :continent_id => 5},
                {:name => 'Dominica', :continent_id => 6},
                {:name => 'Dominican Republic', :continent_id => 6},
                {:name => 'Algeria', :continent_id => 1},
                {:name => 'Ecuador', :continent_id => 7},
                {:name => 'Estonia', :continent_id => 5},
                {:name => 'Egypt', :continent_id => 1},
                {:name => 'Western Sahara', :continent_id => 1},
                {:name => 'Eritrea', :continent_id => 1},
                {:name => 'Spain', :continent_id => 5},
                {:name => 'Ethiopia', :continent_id => 1},
                {:name => 'Finland', :continent_id => 5},
                {:name => 'Fiji', :continent_id => 3},
                {:name => 'Falkland Islands', :continent_id => 7},
                {:name => 'Micronesia', :continent_id => 1},
                {:name => 'Faroe Islands', :continent_id => 5},
                {:name => 'French Southern and Antarctic Territories', :continent_id => 2},
                {:name => 'France', :continent_id => 5},
                {:name => 'Metropolitan France', :continent_id => 5},
                {:name => 'Gabon', :continent_id => 1},
                {:name => 'United Kingdom', :continent_id => 5},
                {:name => 'Grenada', :continent_id => 7},
                {:name => 'Georgia', :continent_id => 5},
                {:name => 'French Guiana', :continent_id => 1},
                {:name => 'Guernsey', :continent_id => 5},
                {:name => 'Ghana', :continent_id => 1},
                {:name => 'Gibraltar', :continent_id => 5},
                {:name => 'Greenland', :continent_id => 6},
                {:name => 'Gambia', :continent_id => 1},
                {:name => 'Guinea', :continent_id => 1},
                {:name => 'Guadeloupe', :continent_id => 7},
                {:name => 'Equatorial Guinea', :continent_id => 1},
                {:name => 'Greece', :continent_id => 5},
                {:name => 'South Georgia and the South Sandwich Islands', :continent_id => 7},
                {:name => 'Guatemala', :continent_id => 6},
                {:name => 'Guam', :continent_id => 6},
                {:name => 'Guinea-Bissau', :continent_id => 1},
                {:name => 'Guyana', :continent_id => 7},
                {:name => 'Hong Kong SAR China', :continent_id => 3},
                {:name => 'Heard Island and McDonald Islands', :continent_id => 2},
                {:name => 'Honduras', :continent_id => 6},
                {:name => 'Croatia', :continent_id => 5},
                {:name => 'Haiti', :continent_id => 7},
                {:name => 'Hungary', :continent_id => 5},
                {:name => 'Indonesia', :continent_id => 3},
                {:name => 'Ireland', :continent_id => 5},
                {:name => 'Israel', :continent_id => 5},
                {:name => 'Isle of Man', :continent_id => 5},
                {:name => 'India', :continent_id => 3},
                {:name => 'British Indian Ocean Territory', :continent_id => 3},
                {:name => 'Iraq', :continent_id => 3},
                {:name => 'Iran', :continent_id => 3},
                {:name => 'Iceland', :continent_id => 5},
                {:name => 'Italy', :continent_id => 5},
                {:name => 'Jersey', :continent_id => 5},
                {:name => 'Jamaica', :continent_id => 6},
                {:name => 'Jordan', :continent_id => 3},
                {:name => 'Japan', :continent_id => 3},
                {:name => 'Johnston Island', :continent_id => 6},
                {:name => 'Kenya', :continent_id => 1},
                {:name => 'Kyrgyzstan', :continent_id => 3},
                {:name => 'Cambodia', :continent_id => 3},
                {:name => 'Kiribati', :continent_id => 6},
                {:name => 'Comoros', :continent_id => 1},
                {:name => 'Saint Kitts and Nevis', :continent_id => 6},
                {:name => 'North Korea', :continent_id => 3},
                {:name => 'South Korea', :continent_id => 3},
                {:name => 'Kuwait', :continent_id => 3},
                {:name => 'Cayman Islands', :continent_id => 6},
                {:name => 'Kazakhstan', :continent_id => 3},
                {:name => 'Laos', :continent_id => 3},
                {:name => 'Lebanon', :continent_id => 3},
                {:name => 'Saint Lucia', :continent_id => 7},
                {:name => 'Liechtenstein', :continent_id => 5},
                {:name => 'Sri Lanka', :continent_id => 3},
                {:name => 'Liberia', :continent_id => 1},
                {:name => 'Lesotho', :continent_id => 1},
                {:name => 'Lithuania', :continent_id => 5},
                {:name => 'Luxembourg', :continent_id => 5},
                {:name => 'Latvia', :continent_id => 5},
                {:name => 'Libya', :continent_id => 1},
                {:name => 'Morocco', :continent_id => 1},
                {:name => 'Monaco', :continent_id => 5},
                {:name => 'Moldova', :continent_id => 5},
                {:name => 'Montenegro', :continent_id => 5},
                {:name => 'Saint Martin', :continent_id => 6},
                {:name => 'Madagascar', :continent_id => 1},
                {:name => 'Marshall Islands', :continent_id => 4},
                {:name => 'Midway Islands', :continent_id => 4},
                {:name => 'Macedonia', :continent_id => 5},
                {:name => 'Mali', :continent_id => 1},
                {:name => 'Myanmar [Burma]', :continent_id => 3},
                {:name => 'Mongolia', :continent_id => 5},
                {:name => 'Macau SAR China', :continent_id => 3},
                {:name => 'Northern Mariana Islands', :continent_id => 3},
                {:name => 'Martinique', :continent_id => 6},
                {:name => 'Mauritania', :continent_id => 1},
                {:name => 'Montserrat', :continent_id => 6},
                {:name => 'Malta', :continent_id => 5},
                {:name => 'Mauritius', :continent_id => 1},
                {:name => 'Maldives', :continent_id => 3},
                {:name => 'Malawi', :continent_id => 1},
                {:name => 'Mexico', :continent_id => 6},
                {:name => 'Malaysia', :continent_id => 3},
                {:name => 'Mozambique', :continent_id => 1},
                {:name => 'Namibia', :continent_id => 1},
                {:name => 'New Caledonia', :continent_id => 4},
                {:name => 'Niger', :continent_id => 1},
                {:name => 'Norfolk Island', :continent_id => 4},
                {:name => 'Nigeria', :continent_id => 1},
                {:name => 'Nicaragua', :continent_id => 6},
                {:name => 'Netherlands', :continent_id => 5},
                {:name => 'Norway', :continent_id => 5},
                {:name => 'Nepal', :continent_id => 3},
                {:name => 'Dronning Maud Land', :continent_id => 2},
                {:name => 'Nauru', :continent_id => 4},
                {:name => 'Neutral Zone'},
                {:name => 'Niue', :continent_id => 4},
                {:name => 'New Zealand', :continent_id => 4},
                {:name => 'Oman', :continent_id => 3},
                {:name => 'Panama', :continent_id => 7},
                {:name => 'Pacific Islands Trust Territory', :continent_id => 3},
                {:name => 'Peru', :continent_id => 7},
                {:name => 'French Polynesia', :continent_id => 4},
                {:name => 'Papua New Guinea', :continent_id => 1},
                {:name => 'Philippines', :continent_id => 3},
                {:name => 'Pakistan', :continent_id => 3},
                {:name => 'Poland', :continent_id => 5},
                {:name => 'Saint Pierre and Miquelon', :continent_id => 6},
                {:name => 'Pitcairn Islands', :continent_id => 7},
                {:name => 'Puerto Rico', :continent_id => 6},
                {:name => 'Palestinian Territories', :continent_id => 3},
                {:name => 'Portugal', :continent_id => 5},
                {:name => 'U.S. Miscellaneous Pacific Islands', :continent_id => 6},
                {:name => 'Palau', :continent_id => 3},
                {:name => 'Paraguay', :continent_id => 7},
                {:name => 'Panama Canal Zone', :continent_id => 7},
                {:name => 'Qatar', :continent_id => 3},
                {:name => 'Reunion', :continent_id => 1},
                {:name => 'Romania', :continent_id => 5},
                {:name => 'Serbia', :continent_id => 5},
                {:name => 'Russia', :continent_id => 5},
                {:name => 'Rwanda', :continent_id => 1},
                {:name => 'Saudi Arabia', :continent_id => 3},
                {:name => 'Solomon Islands', :continent_id => 4},
                {:name => 'Seychelles', :continent_id => 1},
                {:name => 'Sudan', :continent_id => 1},
                {:name => 'Sweden', :continent_id => 5},
                {:name => 'Singapore', :continent_id => 3},
                {:name => 'Saint Helena', :continent_id => 1},
                {:name => 'Slovenia', :continent_id => 5},
                {:name => 'Svalbard and Jan Mayen', :continent_id => 5},
                {:name => 'Slovakia', :continent_id => 5},
                {:name => 'Sierra Leone', :continent_id => 1},
                {:name => 'San Marino', :continent_id => 5},
                {:name => 'Senegal', :continent_id => 1},
                {:name => 'Somalia', :continent_id => 1},
                {:name => 'Suriname', :continent_id => 7},
                {:name => 'Sao Tome and Principe', :continent_id => 1},
                {:name => 'Union of Soviet Socialist Republics', :continent_id => 5},
                {:name => 'El Salvador', :continent_id => 6},
                {:name => 'Syria', :continent_id => 3},
                {:name => 'Swaziland', :continent_id => 1},
                {:name => 'Turks and Caicos Islands', :continent_id => 6},
                {:name => 'Chad', :continent_id => 1},
                {:name => 'French Southern Territories', :continent_id => 1},
                {:name => 'Togo', :continent_id => 1},
                {:name => 'Thailand', :continent_id => 3},
                {:name => 'Tajikistan', :continent_id => 3},
                {:name => 'Tokelau', :continent_id => 4},
                {:name => 'Timor-Leste', :continent_id => 3},
                {:name => 'Turkmenistan', :continent_id => 3},
                {:name => 'Tunisia', :continent_id => 1},
                {:name => 'Tonga', :continent_id => 4},
                {:name => 'Turkey', :continent_id => 3},
                {:name => 'Trinidad and Tobago', :continent_id => 7},
                {:name => 'Tuvalu', :continent_id => 4},
                {:name => 'Taiwan', :continent_id => 3},
                {:name => 'Tanzania', :continent_id => 1},
                {:name => 'Ukraine', :continent_id => 5},
                {:name => 'Uganda', :continent_id => 1},
                {:name => 'U.S. Minor Outlying Islands', :continent_id => 6},
                {:name => 'United States', :continent_id => 6},
                {:name => 'Uruguay', :continent_id => 7},
                {:name => 'Uzbekistan', :continent_id => 3},
                {:name => 'Vatican City', :continent_id => 5},
                {:name => 'Saint Vincent and the Grenadines', :continent_id => 6},
                {:name => 'North Vietnam', :continent_id => 3},
                {:name => 'Venezuela', :continent_id => 7},
                {:name => 'British Virgin Islands', :continent_id => 6},
                {:name => 'U.S. Virgin Islands', :continent_id => 6},
                {:name => 'Vietnam', :continent_id => 3},
                {:name => 'Vanuatu', :continent_id => 4},
                {:name => 'Wallis and Futuna', :continent_id => 4},
                {:name => 'Wake Island', :continent_id => 6},
                {:name => 'Samoa', :continent_id => 4},
                {:name => 'People\'s Democratic Republic of Yemen', :continent_id => 3},
                {:name => 'Yemen', :continent_id => 3},
                {:name => 'Mayotte', :continent_id => 1},
                {:name => 'South Africa', :continent_id => 1},
                {:name => 'Zambia', :continent_id => 1},
                {:name => 'Zimbabwe', :continent_id => 1}]


################################################################################################
################################################################################################
##########                              Products Data                            ###############
################################################################################################
################################################################################################



#Seeding Manufacturers
Manufacturer.create [{ :name => 'Samsung', :slug => 'samsung', :contact_email => 'contact@samsung.com', :country_id => '127'},
					{ :name => 'Sony', :slug => 'sony', :contact_email => 'contact@sony.com', :country_id => '119'}]


#Seeding Products
Product.create [{ :name => 'Galaxy S3', :slug => 'galaxy-s3', :refname => 'GT-I9300', :released_at => '2012-05-01', :long_desc => 'The most powerful smartphone on earth', :manufacturer_id => '1', :category_id => '2'},
                { :name => 'Galaxy S2', :slug => 'galaxy-s2', :refname => 'GT-I9100', :released_at => '2011-05-01', :long_desc => 'The thinnest smartphone on earth', :manufacturer_id => '1', :category_id => '2'}] #2



################################################################################################
################################################################################################
##########                         Operating systems Data                        ###############
################################################################################################
################################################################################################



Product.create [{:refname => "Unicos", :name => "Unicos", :slug => null, :category_id => "11"},
                {:refname => "OS/8", :name => "OS/8", :slug => null, :category_id => "11"},
                {:refname => "Ultrix", :name => "Ultrix", :slug => null, :category_id => "11"},
                {:refname => "Ubuntu JeOS", :name => "Ubuntu JeOS", :slug => null, :category_id => "11"},
                {:refname => "Idris", :name => "Idris", :slug => null, :category_id => "11"},
                {:refname => "Linux-based devices", :name => "Linux-based devices", :slug => null, :category_id => "11"},
                {:refname => "Absolute", :name => "Absolute", :slug => null, :category_id => "11"},
                {:refname => "Damn Small Linux", :name => "Damn Small Linux", :slug => null, :category_id => "11"},
                {:refname => "MS-DOS 2.0", :name => "MS-DOS 2.0", :slug => "1983", :category_id => "11"},
                {:refname => "S60 platform", :name => "S60 platform", :slug => null, :category_id => "11"},
                {:refname => "VM", :name => "VM", :slug => null, :category_id => "11"},
                {:refname => "Mac OS", :name => "Mac OS", :slug => "1984", :category_id => "11"},
                {:refname => "TinyKRNL", :name => "TinyKRNL", :slug => null, :category_id => "11"},
                {:refname => "Kubuntu", :name => "Kubuntu", :slug => "2006", :category_id => "11"},
                {:refname => "Super OS", :name => "Super OS", :slug => null, :category_id => "11"},
                {:refname => "Tru64 UNIX", :name => "Tru64 UNIX", :slug => null, :category_id => "11"},
                {:refname => "Windows Vista Business", :name => "Windows Vista Business", :slug => null, :category_id => "11"},
                {:refname => "Ubuntu Studio", :name => "Ubuntu Studio", :slug => null, :category_id => "11"},
                {:refname => "ChibiOS/RT", :name => "ChibiOS/RT", :slug => null, :category_id => "11"},
                {:refname => "Apple DOS", :name => "Apple DOS", :slug => null, :category_id => "11"},
                {:refname => "Cisco IOS", :name => "Cisco IOS", :slug => null, :category_id => "11"},
                {:refname => "Windows Phone 7.1", :name => "Windows Phone 7.1", :slug => null, :category_id => "11"},
                {:refname => "Syllable", :name => "Syllable", :slug => null, :category_id => "11"},
                {:refname => "Windows Phone 8", :name => "Windows Phone 8", :slug => null, :category_id => "11"},
                {:refname => "Freeware", :name => "Freeware", :slug => null, :category_id => "11"},
                {:refname => "DOS/VS", :name => "DOS/VS", :slug => null, :category_id => "11"},
                {:refname => "RT-Thread", :name => "RT-Thread", :slug => null, :category_id => "11"},
                {:refname => "Rocks Cluster Distribution", :name => "Rocks Cluster Distribution", :slug => null, :category_id => "11"},
                {:refname => "Whitix", :name => "Whitix", :slug => null, :category_id => "11"},
                {:refname => "MIE Linux", :name => "MIE Linux", :slug => "2008", :category_id => "11"},
                {:refname => "Ubuntu 9.10", :name => "Ubuntu 9.10", :slug => "2009", :category_id => "11"},
                {:refname => "Linux", :name => "Linux", :slug => null, :category_id => "11"},
                {:refname => "Aurora SPARC Linux", :name => "Aurora SPARC Linux", :slug => null, :category_id => "11"},
                {:refname => "Windows 98", :name => "Windows 98", :slug => null, :category_id => "11"},
                {:refname => "SLAX", :name => "SLAX", :slug => "2006", :category_id => "11"},
                {:refname => "IS-DOS", :name => "IS-DOS", :slug => null, :category_id => "11"},
                {:refname => "Mac OS X v10.1", :name => "Mac OS X v10.1", :slug => "2001", :category_id => "11"},
                {:refname => "Fusion RTOS", :name => "Fusion RTOS", :slug => null, :category_id => "11"},
                {:refname => "Ultimate Edition", :name => "Ultimate Edition", :slug => null, :category_id => "11"},
                {:refname => "Nokia 9210", :name => "Nokia 9210", :slug => null, :category_id => "11"},
                {:refname => "Windows Server 2008 for Itanium-based Systems", :name => "Windows Server 2008 for Itanium-based Systems", :slug => null, :category_id => "11"},
                {:refname => "Berkeley Timesharing System", :name => "Berkeley Timesharing System", :slug => null, :category_id => "11"},
                {:refname => "Parted Magic", :name => "Parted Magic", :slug => null, :category_id => "11"},
                {:refname => "Vector Linux", :name => "Vector Linux", :slug => "2006", :category_id => "11"},
                {:refname => "Argante", :name => "Argante", :slug => null, :category_id => "11"},
                {:refname => "Elive", :name => "Elive", :slug => null, :category_id => "11"},
                {:refname => "VM/386", :name => "VM/386", :slug => null, :category_id => "11"},
                {:refname => "GoblinX", :name => "GoblinX", :slug => null, :category_id => "11"},
                {:refname => "SUSE Linux Enterprise Server", :name => "SUSE Linux Enterprise Server", :slug => null, :category_id => "11"},
                {:refname => "Kubuntu 11.04", :name => "Kubuntu 11.04", :slug => null, :category_id => "11"},
                {:refname => "Windows Server 2012", :name => "Windows Server 2012", :slug => "2012", :category_id => "11"},
                {:refname => "CP-823/U", :name => "CP-823/U", :slug => null, :category_id => "11"},
                {:refname => "UNIX System V", :name => "UNIX System V", :slug => null, :category_id => "11"},
                {:refname => "MEPIS", :name => "MEPIS", :slug => "2009", :category_id => "11"},
                {:refname => "Foresight Linux", :name => "Foresight Linux", :slug => "2007", :category_id => "11"},
                {:refname => "Mac OS X v10.6", :name => "Mac OS X v10.6", :slug => "2009", :category_id => "11"},
                {:refname => "Cray Operating System", :name => "Cray Operating System", :slug => null, :category_id => "11"},
                {:refname => "Windows Web Server 2008", :name => "Windows Web Server 2008", :slug => null, :category_id => "11"},
                {:refname => "Research Unix", :name => "Research Unix", :slug => null, :category_id => "11"},
                {:refname => "Windows NT", :name => "Windows NT", :slug => "1993", :category_id => "11"},
                {:refname => "Multics", :name => "Multics", :slug => null, :category_id => "11"},
                {:refname => "GP2X Wiz", :name => "GP2X Wiz", :slug => null, :category_id => "11"},
                {:refname => "E/OS", :name => "E/OS", :slug => null, :category_id => "11"},
                {:refname => "Windows Storage Server 2008", :name => "Windows Storage Server 2008", :slug => null, :category_id => "11"},
                {:refname => "Newton OS", :name => "Newton OS", :slug => null, :category_id => "11"},
                {:refname => "BSD/OS", :name => "BSD/OS", :slug => null, :category_id => "11"},
                {:refname => "FreeBSD 2.1.5", :name => "FreeBSD 2.1.5", :slug => null, :category_id => "11"},
                {:refname => "TR-DOS", :name => "TR-DOS", :slug => null, :category_id => "11"},
                {:refname => "GP2X", :name => "GP2X", :slug => null, :category_id => "11"},
                {:refname => "FMI/OS", :name => "FMI/OS", :slug => null, :category_id => "11"},
                {:refname => "DEC BATCH-11/DOS-11", :name => "DEC BATCH-11/DOS-11", :slug => null, :category_id => "11"},
                {:refname => "Yellow Dog Linux", :name => "Yellow Dog Linux", :slug => null, :category_id => "11"},
                {:refname => "86-DOS", :name => "86-DOS", :slug => null, :category_id => "11"},
                {:refname => "AD-75", :name => "AD-75", :slug => null, :category_id => "11"},
                {:refname => "Maemo", :name => "Maemo", :slug => null, :category_id => "11"},
                {:refname => "TUD:OS", :name => "TUD:OS", :slug => null, :category_id => "11"},
                {:refname => "SymbOS", :name => "SymbOS", :slug => null, :category_id => "11"},
                {:refname => "BKUNIX", :name => "BKUNIX", :slug => null, :category_id => "11"},
                {:refname => "Atomix", :name => "Atomix", :slug => null, :category_id => "11"},
                {:refname => "Linkat", :name => "Linkat", :slug => null, :category_id => "11"},
                {:refname => "PC DOS 1.0", :name => "PC DOS 1.0", :slug => null, :category_id => "11"},
                {:refname => "Ubuntu Netbook Remix", :name => "Ubuntu Netbook Remix", :slug => null, :category_id => "11"},
                {:refname => "SUPER-UX", :name => "SUPER-UX", :slug => null, :category_id => "11"},
                {:refname => "Slackware", :name => "Slackware", :slug => null, :category_id => "11"},
                {:refname => "Google Chrome OS", :name => "Google Chrome OS", :slug => null, :category_id => "11"},
                {:refname => "Windows Server 2003", :name => "Windows Server 2003", :slug => "2003", :category_id => "11"},
                {:refname => "Windows Server 2008 Enterprise Edition", :name => "Windows Server 2008 Enterprise Edition", :slug => null, :category_id => "11"},
                {:refname => "ROS", :name => "ROS", :slug => null, :category_id => "11"},
                {:refname => "System Software 6", :name => "System Software 6", :slug => "1988", :category_id => "11"},
                {:refname => "PC DOS 7.0", :name => "PC DOS 7.0", :slug => null, :category_id => "11"},
                {:refname => "Windows 2000 Datacenter Server", :name => "Windows 2000 Datacenter Server", :slug => null, :category_id => "11"},
                {:refname => "Unix/NS", :name => "Unix/NS", :slug => null, :category_id => "11"},
                {:refname => "Gentoo Linux", :name => "Gentoo Linux", :slug => "2002", :category_id => "11"},
                {:refname => "Xandros Server", :name => "Xandros Server", :slug => null, :category_id => "11"},
                {:refname => "Pintos", :name => "Pintos", :slug => null, :category_id => "11"},
                {:refname => "Plan 9", :name => "Plan 9", :slug => "1992", :category_id => "11"},
                {:refname => "JNode", :name => "JNode", :slug => null, :category_id => "11"},
                {:refname => "Real-time operating system", :name => "Real-time operating system", :slug => null, :category_id => "11"},
                {:refname => "Derrick Operating System", :name => "Derrick Operating System", :slug => null, :category_id => "11"},
                {:refname => "Pandora", :name => "Pandora", :slug => null, :category_id => "11"},
                {:refname => "FreeBSD 4.x", :name => "FreeBSD 4.x", :slug => null, :category_id => "11"},
                {:refname => "DOS/360", :name => "DOS/360", :slug => null, :category_id => "11"},
                {:refname => "FreeBSD 4.8", :name => "FreeBSD 4.8", :slug => null, :category_id => "11"},
                {:refname => "Windows XP Professional x64 Edition", :name => "Windows XP Professional x64 Edition", :slug => null, :category_id => "11"},
                {:refname => "Windows 3.0", :name => "Windows 3.0", :slug => null, :category_id => "11"},
                {:refname => "SMSall", :name => "SMSall", :slug => null, :category_id => "11"},
                {:refname => "RSX-11", :name => "RSX-11", :slug => null, :category_id => "11"},
                {:refname => "386BSD", :name => "386BSD", :slug => "1992", :category_id => "11"},
                {:refname => "Ubuntu 11.04", :name => "Ubuntu 11.04", :slug => "2011", :category_id => "11"},
                {:refname => "Funtoo", :name => "Funtoo", :slug => null, :category_id => "11"},
                {:refname => "VA Kernel", :name => "VA Kernel", :slug => null, :category_id => "11"},
                {:refname => "RISC OS", :name => "RISC OS", :slug => null, :category_id => "11"},
                {:refname => "Windows Vista", :name => "Windows Vista", :slug => "2007", :category_id => "11"},
                {:refname => "SharpOS", :name => "SharpOS", :slug => null, :category_id => "11"},
                {:refname => "Red Hat Enterprise Linux", :name => "Red Hat Enterprise Linux", :slug => null, :category_id => "11"},
                {:refname => "Windows Mobile", :name => "Windows Mobile", :slug => null, :category_id => "11"},
                {:refname => "CRUX", :name => "CRUX", :slug => null, :category_id => "11"},
                {:refname => "Linspire", :name => "Linspire", :slug => null, :category_id => "11"},
                {:refname => "LUnix", :name => "LUnix", :slug => null, :category_id => "11"},
                {:refname => "Apple Pascal", :name => "Apple Pascal", :slug => null, :category_id => "11"},
                {:refname => "Phoenix OS", :name => "Phoenix OS", :slug => null, :category_id => "11"},
                {:refname => "FreeBSD 1.1.5", :name => "FreeBSD 1.1.5", :slug => null, :category_id => "11"},
                {:refname => "Windows XP Tablet PC Edition", :name => "Windows XP Tablet PC Edition", :slug => null, :category_id => "11"},
                {:refname => "VxWorks", :name => "VxWorks", :slug => null, :category_id => "11"},
                {:refname => "Sinclair BASIC", :name => "Sinclair BASIC", :slug => null, :category_id => "11"},
                {:refname => "Kubuntu 6.06 LTS", :name => "Kubuntu 6.06 LTS", :slug => "2006", :category_id => "11"},
                {:refname => "GnuLinEx", :name => "GnuLinEx", :slug => null, :category_id => "11"},
                {:refname => "AmigaOS", :name => "AmigaOS", :slug => null, :category_id => "11"},
                {:refname => "BBC Micro", :name => "BBC Micro", :slug => null, :category_id => "11"},
                {:refname => "Kororaa", :name => "Kororaa", :slug => null, :category_id => "11"},
                {:refname => "Pentoo", :name => "Pentoo", :slug => null, :category_id => "11"},
                {:refname => "Ubuntu Buddhist Remix", :name => "Ubuntu Buddhist Remix", :slug => null, :category_id => "11"},
                {:refname => "CTSS", :name => "CTSS", :slug => null, :category_id => "11"},
                {:refname => "Fedora Core", :name => "Fedora Core", :slug => "2003", :category_id => "11"},
                {:refname => "FreeBSD 1.1", :name => "FreeBSD 1.1", :slug => null, :category_id => "11"},
                {:refname => "Chrysalis", :name => "Chrysalis", :slug => null, :category_id => "11"},
                {:refname => "Windows NT 3.1", :name => "Windows NT 3.1", :slug => "1993", :category_id => "11"},
                {:refname => "Windows Server 2000", :name => "Windows Server 2000", :slug => null, :category_id => "11"},
                {:refname => "Internet Explorer", :name => "Internet Explorer", :slug => null, :category_id => "11"},
                {:refname => "CAos Linux", :name => "CAos Linux", :slug => null, :category_id => "11"},
                {:refname => "PC-DOS", :name => "PC-DOS", :slug => "1981", :category_id => "11"},
                {:refname => "Windows XP", :name => "Windows XP", :slug => "2001", :category_id => "11"},
                {:refname => "Drupal", :name => "Drupal", :slug => null, :category_id => "11"},
                {:refname => "MS-DOS 4.0", :name => "MS-DOS 4.0", :slug => "1988", :category_id => "11"},
                {:refname => "Tuga", :name => "Tuga", :slug => null, :category_id => "11"},
                {:refname => "Red Hat Linux", :name => "Red Hat Linux", :slug => null, :category_id => "11"},
                {:refname => "FreeBSD 2.1", :name => "FreeBSD 2.1", :slug => null, :category_id => "11"},
                {:refname => "Inferno", :name => "Inferno", :slug => null, :category_id => "11"},
                {:refname => "Fedora Core 3", :name => "Fedora Core 3", :slug => null, :category_id => "11"},
                {:refname => "Windows XP Starter Edition", :name => "Windows XP Starter Edition", :slug => null, :category_id => "11"},
                {:refname => "PCLinuxOS", :name => "PCLinuxOS", :slug => "2007", :category_id => "11"},
                {:refname => "UserLinux", :name => "UserLinux", :slug => null, :category_id => "11"},
                {:refname => "Mac OS X v10.2", :name => "Mac OS X v10.2", :slug => null, :category_id => "11"},
                {:refname => "Talon DSP RTOS", :name => "Talon DSP RTOS", :slug => null, :category_id => "11"},
                {:refname => "Windows 8", :name => "Windows 8", :slug => null, :category_id => "11"},
                {:refname => "BeOS", :name => "BeOS", :slug => null, :category_id => "11"},
                {:refname => "Amiga OS 2.0", :name => "Amiga OS 2.0", :slug => null, :category_id => "11"},
                {:refname => "TRON Project", :name => "TRON Project", :slug => "1984", :category_id => "11"},
                {:refname => "Native Oberon", :name => "Native Oberon", :slug => null, :category_id => "11"},
                {:refname => "OpenVMS", :name => "OpenVMS", :slug => null, :category_id => "11"},
                {:refname => "SabayonLinux", :name => "SabayonLinux", :slug => null, :category_id => "11"},
                {:refname => "TOPS-20", :name => "TOPS-20", :slug => null, :category_id => "11"},
                {:refname => "FLEX", :name => "FLEX", :slug => "1976", :category_id => "11"},
                {:refname => "FreeDOS", :name => "FreeDOS", :slug => null, :category_id => "11"},
                {:refname => "FreeBSD 2.0.5", :name => "FreeBSD 2.0.5", :slug => null, :category_id => "11"},
                {:refname => "Tinix", :name => "Tinix", :slug => null, :category_id => "11"},
                {:refname => "Xandros Desktop", :name => "Xandros Desktop", :slug => null, :category_id => "11"},
                {:refname => "Minix", :name => "Minix", :slug => null, :category_id => "11"},
                {:refname => "OS/360", :name => "OS/360", :slug => null, :category_id => "11"},
                {:refname => "Mona", :name => "Mona", :slug => null, :category_id => "11"},
                {:refname => "Kubuntu 9.04", :name => "Kubuntu 9.04", :slug => null, :category_id => "11"},
                {:refname => "DNIX", :name => "DNIX", :slug => null, :category_id => "11"},
                {:refname => "Ntoskrnl.exe", :name => "Ntoskrnl.exe", :slug => null, :category_id => "11"},
                {:refname => "Web browser", :name => "Web browser", :slug => null, :category_id => "11"},
                {:refname => "Stratus VOS", :name => "Stratus VOS", :slug => null, :category_id => "11"},
                {:refname => "Mac OS X Server", :name => "Mac OS X Server", :slug => null, :category_id => "11"},
                {:refname => "Windows Vista Ultimate", :name => "Windows Vista Ultimate", :slug => "2007", :category_id => "11"},
                {:refname => "Fedora Core 5", :name => "Fedora Core 5", :slug => null, :category_id => "11"},
                {:refname => "AmiQNX", :name => "AmiQNX", :slug => null, :category_id => "11"},
                {:refname => "Amiga", :name => "Amiga", :slug => null, :category_id => "11"},
                {:refname => "PikeOS", :name => "PikeOS", :slug => null, :category_id => "11"},
                {:refname => "Fluxbuntu", :name => "Fluxbuntu", :slug => null, :category_id => "11"},
                {:refname => "RC 4000 Multiprogramming System", :name => "RC 4000 Multiprogramming System", :slug => null, :category_id => "11"},
                {:refname => "Berkeley Software Distribution", :name => "Berkeley Software Distribution", :slug => "1977", :category_id => "11"},
                {:refname => "Mozilla Firefox", :name => "Mozilla Firefox", :slug => null, :category_id => "11"},
                {:refname => "QNX", :name => "QNX", :slug => null, :category_id => "11"},
                {:refname => "UnixWare", :name => "UnixWare", :slug => null, :category_id => "11"},
                {:refname => "Windows 2000 Advanced Server", :name => "Windows 2000 Advanced Server", :slug => null, :category_id => "11"},
                {:refname => "WebOS", :name => "WebOS", :slug => "2009", :category_id => "11"},
                {:refname => "MCNLive", :name => "MCNLive", :slug => null, :category_id => "11"},
                {:refname => "Kayou", :name => "Kayou", :slug => null, :category_id => "11"},
                {:refname => "Contiki", :name => "Contiki", :slug => null, :category_id => "11"},
                {:refname => "Ark Linux", :name => "Ark Linux", :slug => null, :category_id => "11"},
                {:refname => "DOS", :name => "DOS", :slug => null, :category_id => "11"},
                {:refname => "Fedora Core 2", :name => "Fedora Core 2", :slug => null, :category_id => "11"},
                {:refname => "Windows 7", :name => "Windows 7", :slug => "2009", :category_id => "11"},
                {:refname => "Mandriva Linux", :name => "Mandriva Linux", :slug => null, :category_id => "11"},
                {:refname => "BeOS R5", :name => "BeOS R5", :slug => null, :category_id => "11"},
                {:refname => "HP-UX", :name => "HP-UX", :slug => null, :category_id => "11"},
                {:refname => "Ubuntu", :name => "Ubuntu", :slug => "2004", :category_id => "11"},
                {:refname => "Windows NT 4.0 Embedded", :name => "Windows NT 4.0 Embedded", :slug => null, :category_id => "11"},
                {:refname => "TSS-8", :name => "TSS-8", :slug => null, :category_id => "11"},
                {:refname => "FreeBSD 2.1.7", :name => "FreeBSD 2.1.7", :slug => null, :category_id => "11"},
                {:refname => "Kaneton", :name => "Kaneton", :slug => null, :category_id => "11"},
                {:refname => "Fedora 7", :name => "Fedora 7", :slug => null, :category_id => "11"},
                {:refname => "386BSD", :name => "386BSD", :slug => null, :category_id => "11"},
                {:refname => "HydrixOS", :name => "HydrixOS", :slug => null, :category_id => "11"},
                {:refname => "SPIN", :name => "SPIN", :slug => null, :category_id => "11"},
                {:refname => "PC-UX", :name => "PC-UX", :slug => null, :category_id => "11"},
                {:refname => "EVEREST Linux", :name => "EVEREST Linux", :slug => null, :category_id => "11"},
                {:refname => "ReactOS", :name => "ReactOS", :slug => null, :category_id => "11"},
                {:refname => "Kubuntu 5.04", :name => "Kubuntu 5.04", :slug => "2005", :category_id => "11"},
                {:refname => "Trix", :name => "Trix", :slug => null, :category_id => "11"},
                {:refname => "Mac OS X Server 1.0", :name => "Mac OS X Server 1.0", :slug => "1999", :category_id => "11"},
                {:refname => "SCO OpenServer", :name => "SCO OpenServer", :slug => null, :category_id => "11"},
                {:refname => "Kubuntu 7.04", :name => "Kubuntu 7.04", :slug => "2007", :category_id => "11"},
                {:refname => "Mac OS X", :name => "Mac OS X", :slug => "2001", :category_id => "11"},
                {:refname => "Spring operating system", :name => "Spring operating system", :slug => null, :category_id => "11"},
                {:refname => "MSX BASIC", :name => "MSX BASIC", :slug => null, :category_id => "11"},
                {:refname => "Trustix", :name => "Trustix", :slug => null, :category_id => "11"},
                {:refname => "Vanguard microkernel", :name => "Vanguard microkernel", :slug => null, :category_id => "11"},
                {:refname => "MS-DOS 7.0", :name => "MS-DOS 7.0", :slug => "1995", :category_id => "11"},
                {:refname => "Finder", :name => "Finder", :slug => null, :category_id => "11"},
                {:refname => "Atari DOS", :name => "Atari DOS", :slug => null, :category_id => "11"},
                {:refname => "Mac OS X v10.3", :name => "Mac OS X v10.3", :slug => null, :category_id => "11"},
                {:refname => "Ultimate", :name => "Ultimate", :slug => null, :category_id => "11"},
                {:refname => "FreeBSD 2.1.6", :name => "FreeBSD 2.1.6", :slug => null, :category_id => "11"},
                {:refname => "FreeBSD 2.2", :name => "FreeBSD 2.2", :slug => null, :category_id => "11"},
                {:refname => "MS/8", :name => "MS/8", :slug => null, :category_id => "11"},
                {:refname => "SOS", :name => "SOS", :slug => null, :category_id => "11"},
                {:refname => "Caixa MÃ¡gica", :name => "Caixa MÃ¡gica", :slug => null, :category_id => "11"},
                {:refname => "Minerva", :name => "Minerva", :slug => null, :category_id => "11"},
                {:refname => "Asianux", :name => "Asianux", :slug => null, :category_id => "11"},
                {:refname => "Cygwin", :name => "Cygwin", :slug => null, :category_id => "11"},
                {:refname => "Commodore 64", :name => "Commodore 64", :slug => null, :category_id => "11"},
                {:refname => "Google Chrome", :name => "Google Chrome", :slug => null, :category_id => "11"},
                {:refname => "Extremely Reliable Operating System", :name => "Extremely Reliable Operating System", :slug => null, :category_id => "11"},
                {:refname => "GP32", :name => "GP32", :slug => null, :category_id => "11"},
                {:refname => "Windows 3.1x", :name => "Windows 3.1x", :slug => "1992", :category_id => "11"},
                {:refname => "Coyotos", :name => "Coyotos", :slug => null, :category_id => "11"},
                {:refname => "HPBSD", :name => "HPBSD", :slug => null, :category_id => "11"},
                {:refname => "Mac OS X Lion", :name => "Mac OS X Lion", :slug => "2011", :category_id => "11"},
                {:refname => "CapROS", :name => "CapROS", :slug => null, :category_id => "11"},
                {:refname => "Honeycomb", :name => "Honeycomb", :slug => 2011, :category_id => "11"},
                {:refname => "Dreamlinux", :name => "Dreamlinux", :slug => null, :category_id => "11"},
                {:refname => "Nukernel", :name => "Nukernel", :slug => null, :category_id => "11"},
                {:refname => "A/UX", :name => "A/UX", :slug => null, :category_id => "11"},
                {:refname => "Solaris Operating System", :name => "Solaris Operating System", :slug => null, :category_id => "11"},
                {:refname => "Windows Me", :name => "Windows Me", :slug => null, :category_id => "11"},
                {:refname => "Linux", :name => "Linux", :slug => null, :category_id => "11"},
                {:refname => "Plurix", :name => "Plurix", :slug => null, :category_id => "11"},
                {:refname => "Windows Server 2008", :name => "Windows Server 2008", :slug => null, :category_id => "11"},
                {:refname => "iOS 6", :name => "iOS 6", :slug => "2012", :category_id => "11"},
                {:refname => "Corel Linux", :name => "Corel Linux", :slug => null, :category_id => "11"},
                {:refname => "FreeBSD 2.2.1", :name => "FreeBSD 2.2.1", :slug => null, :category_id => "11"},
                {:refname => "DG/UX", :name => "DG/UX", :slug => null, :category_id => "11"},
                {:refname => "Frugalware", :name => "Frugalware", :slug => "2007", :category_id => "11"},
                {:refname => "Cray Time Sharing System", :name => "Cray Time Sharing System", :slug => null, :category_id => "11"},
                {:refname => "MicroEmpix", :name => "MicroEmpix", :slug => null, :category_id => "11"},
                {:refname => "Softlanding Linux System", :name => "Softlanding Linux System", :slug => null, :category_id => "11"},
                {:refname => "U-lite", :name => "U-lite", :slug => null, :category_id => "11"},
                {:refname => "Xenix", :name => "Xenix", :slug => null, :category_id => "11"},
                {:refname => "Zenwalk Linux", :name => "Zenwalk Linux", :slug => "2005", :category_id => "11"},
                {:refname => "JX", :name => "JX", :slug => null, :category_id => "11"},
                {:refname => "Haiku", :name => "Haiku", :slug => null, :category_id => "11"},
                {:refname => "PC DOS 2.0", :name => "PC DOS 2.0", :slug => null, :category_id => "11"},
                {:refname => "Mac OS 7", :name => "Mac OS 7", :slug => "1991", :category_id => "11"},
                {:refname => "Xinu", :name => "Xinu", :slug => null, :category_id => "11"},
                {:refname => "Sinclair QDOS", :name => "Sinclair QDOS", :slug => null, :category_id => "11"},
                {:refname => "Windows Server 2008 Datacenter Edition", :name => "Windows Server 2008 Datacenter Edition", :slug => null, :category_id => "11"},
                {:refname => "Miraculix", :name => "Miraculix", :slug => null, :category_id => "11"},
                {:refname => "VeritOS", :name => "VeritOS", :slug => null, :category_id => "11"},
                {:refname => "OS/2", :name => "OS/2", :slug => null, :category_id => "11"},
                {:refname => "Granular Linux", :name => "Granular Linux", :slug => null, :category_id => "11"},
                {:refname => "L3 microkernel", :name => "L3 microkernel", :slug => null, :category_id => "11"},
                {:refname => "Dingoo", :name => "Dingoo", :slug => null, :category_id => "11"},
                {:refname => "Pinguy OS", :name => "Pinguy OS", :slug => null, :category_id => "11"},
                {:refname => "GNU/Linux", :name => "GNU/Linux", :slug => null, :category_id => "11"},
                {:refname => "SCOPE", :name => "SCOPE", :slug => null, :category_id => "11"},
                {:refname => "Windows NT 4.0", :name => "Windows NT 4.0", :slug => "1996", :category_id => "11"},
                {:refname => "Windows Vista Home Premium", :name => "Windows Vista Home Premium", :slug => null, :category_id => "11"},
                {:refname => "Kubuntu 5.10", :name => "Kubuntu 5.10", :slug => "2005", :category_id => "11"},
                {:refname => "PC DOS 3.3", :name => "PC DOS 3.3", :slug => null, :category_id => "11"},
                {:refname => "Oberon operating system", :name => "Oberon operating system", :slug => null, :category_id => "11"},
                {:refname => "Annvix", :name => "Annvix", :slug => null, :category_id => "11"},
                {:refname => "Fermi Linux", :name => "Fermi Linux", :slug => null, :category_id => "11"},
                {:refname => "YOPER", :name => "YOPER", :slug => null, :category_id => "11"},
                {:refname => "KDE Software Compilation", :name => "KDE Software Compilation", :slug => null, :category_id => "11"},
                {:refname => "Unix", :name => "Unix", :slug => null, :category_id => "11"},
                {:refname => "Linux", :name => "Linux", :slug => null, :category_id => "11"},
                {:refname => "ALinux", :name => "ALinux", :slug => null, :category_id => "11"},
                {:refname => "ECos", :name => "ECos", :slug => null, :category_id => "11"},
                {:refname => "DragonFly BSD", :name => "DragonFly BSD", :slug => null, :category_id => "11"},
                {:refname => "GNU/DOS", :name => "GNU/DOS", :slug => null, :category_id => "11"},
                {:refname => "RADIX-50", :name => "RADIX-50", :slug => null, :category_id => "11"},
                {:refname => "TinyMe", :name => "TinyMe", :slug => null, :category_id => "11"},
                {:refname => "GNU/NetBSD", :name => "GNU/NetBSD", :slug => null, :category_id => "11"},
                {:refname => "KolibriOS", :name => "KolibriOS", :slug => null, :category_id => "11"},
                {:refname => "White Box Enterprise Linux", :name => "White Box Enterprise Linux", :slug => null, :category_id => "11"},
                {:refname => "Mac OS X v10.0", :name => "Mac OS X v10.0", :slug => "2001", :category_id => "11"},
                {:refname => "Fedora Core 6", :name => "Fedora Core 6", :slug => null, :category_id => "11"},
                {:refname => "AROS Research Operating System", :name => "AROS Research Operating System", :slug => null, :category_id => "11"},
                {:refname => "VSTa", :name => "VSTa", :slug => null, :category_id => "11"},
                {:refname => "Fedora Core 1", :name => "Fedora Core 1", :slug => null, :category_id => "11"},
                {:refname => "EmuTOS", :name => "EmuTOS", :slug => null, :category_id => "11"},
                {:refname => "TUNIS", :name => "TUNIS", :slug => null, :category_id => "11"},
                {:refname => "Easy Peasy", :name => "Easy Peasy", :slug => null, :category_id => "11"},
                {:refname => "Phoenix-RTOS", :name => "Phoenix-RTOS", :slug => null, :category_id => "11"},
                {:refname => "SystemRescueCD", :name => "SystemRescueCD", :slug => null, :category_id => "11"},
                {:refname => "FreeBSD 2.2.5", :name => "FreeBSD 2.2.5", :slug => null, :category_id => "11"},
                {:refname => "Mythbuntu", :name => "Mythbuntu", :slug => null, :category_id => "11"},
                {:refname => "OSF/1", :name => "OSF/1", :slug => null, :category_id => "11"},
                {:refname => "PC DOS 2000", :name => "PC DOS 2000", :slug => null, :category_id => "11"},
                {:refname => "PC DOS 6.0", :name => "PC DOS 6.0", :slug => null, :category_id => "11"},
                {:refname => "Coherent", :name => "Coherent", :slug => "1983", :category_id => "11"},
                {:refname => "SAM Linux", :name => "SAM Linux", :slug => null, :category_id => "11"},
                {:refname => "Mac OS 9", :name => "Mac OS 9", :slug => "1999", :category_id => "11"},
                {:refname => "ÎœnOS", :name => "ÎœnOS", :slug => null, :category_id => "11"},
                {:refname => "Xubuntu", :name => "Xubuntu", :slug => null, :category_id => "11"},
                {:refname => "OpenIndiana", :name => "OpenIndiana", :slug => null, :category_id => "11"},
                {:refname => "Jari OS", :name => "Jari OS", :slug => null, :category_id => "11"},
                {:refname => "L4 microkernel family", :name => "L4 microkernel family", :slug => null, :category_id => "11"},
                {:refname => "K42", :name => "K42", :slug => null, :category_id => "11"},
                {:refname => "OpenBSD", :name => "OpenBSD", :slug => "2008", :category_id => "11"},
                {:refname => "Eumel", :name => "Eumel", :slug => null, :category_id => "11"},
                {:refname => "Windows HPC Server 2008", :name => "Windows HPC Server 2008", :slug => null, :category_id => "11"},
                {:refname => "Microsoft Windows", :name => "Microsoft Windows", :slug => "1985", :category_id => "11"},
                {:refname => "FreeRTOS", :name => "FreeRTOS", :slug => null, :category_id => "11"},
                {:refname => "Windows Vista Home Basic", :name => "Windows Vista Home Basic", :slug => null, :category_id => "11"},
                {:refname => "Debian GNU/Linux", :name => "Debian GNU/Linux", :slug => "1993", :category_id => "11"},
                {:refname => "GNU", :name => "GNU", :slug => null, :category_id => "11"},
                {:refname => "SMSQ/E", :name => "SMSQ/E", :slug => null, :category_id => "11"},
                {:refname => "FreeVMS", :name => "FreeVMS", :slug => null, :category_id => "11"},
                {:refname => "Qtopia", :name => "Qtopia", :slug => null, :category_id => "11"},
                {:refname => "Z-DOS", :name => "Z-DOS", :slug => null, :category_id => "11"},
                {:refname => "PSOS", :name => "PSOS", :slug => "1982", :category_id => "11"},
                {:refname => "Vine Linux", :name => "Vine Linux", :slug => null, :category_id => "11"},
                {:refname => "MS-DOS 5.0", :name => "MS-DOS 5.0", :slug => "1991", :category_id => "11"},
                {:refname => "Sirius RTOS", :name => "Sirius RTOS", :slug => null, :category_id => "11"},
                {:refname => "DOS Plus", :name => "DOS Plus", :slug => null, :category_id => "11"},
                {:refname => "Dex4u", :name => "Dex4u", :slug => null, :category_id => "11"},
                {:refname => "WPS-8", :name => "WPS-8", :slug => null, :category_id => "11"},
                {:refname => "Z/OS", :name => "Z/OS", :slug => null, :category_id => "11"},
                {:refname => "INTERACTIVE UNIX", :name => "INTERACTIVE UNIX", :slug => null, :category_id => "11"},
                {:refname => "Ice Cream Sandwich", :name => "Ice Cream Sandwich", :slug => "2011", :category_id => "11"},
                {:refname => "FreeBSD 2.0", :name => "FreeBSD 2.0", :slug => null, :category_id => "11"},
                {:refname => "4.3BSD NET/2", :name => "4.3BSD NET/2", :slug => null, :category_id => "11"},
                {:refname => "Sprite operating system", :name => "Sprite operating system", :slug => null, :category_id => "11"},
                {:refname => "Fedora", :name => "Fedora", :slug => null, :category_id => "11"},
                {:refname => "Game Boy Advance", :name => "Game Boy Advance", :slug => null, :category_id => "11"},
                {:refname => "IRIX", :name => "IRIX", :slug => null, :category_id => "11"},
                {:refname => "SUSE Linux Enterprise Desktop", :name => "SUSE Linux Enterprise Desktop", :slug => null, :category_id => "11"},
                {:refname => "Sidux", :name => "Sidux", :slug => null, :category_id => "11"},
                {:refname => "Berry Linux", :name => "Berry Linux", :slug => null, :category_id => "11"},
                {:refname => "DOS/BATCH 11", :name => "DOS/BATCH 11", :slug => null, :category_id => "11"},
                {:refname => "MSX-DOS", :name => "MSX-DOS", :slug => null, :category_id => "11"},
                {:refname => "Hydra", :name => "Hydra", :slug => null, :category_id => "11"},
                {:refname => "Autocad", :name => "Autocad", :slug => null, :category_id => "11"},
                {:refname => "linuX-gamers", :name => "linuX-gamers", :slug => null, :category_id => "11"},
                {:refname => "Kubuntu 7.10", :name => "Kubuntu 7.10", :slug => "2007", :category_id => "11"},
                {:refname => "Pilot", :name => "Pilot", :slug => "1977", :category_id => "11"},
                {:refname => "BackTrack", :name => "BackTrack", :slug => null, :category_id => "11"},
                {:refname => "Symbian", :name => "Symbian", :slug => null, :category_id => "11"},
                {:refname => "Atari TOS", :name => "Atari TOS", :slug => null, :category_id => "11"},
                {:refname => "Co-CreateLinux", :name => "Co-CreateLinux", :slug => null, :category_id => "11"},
                {:refname => "EnterpriseBSD", :name => "EnterpriseBSD", :slug => null, :category_id => "11"},
                {:refname => "Derrick Operating System", :name => "Derrick Operating System", :slug => null, :category_id => "11"},
                {:refname => "POSIX", :name => "POSIX", :slug => null, :category_id => "11"},
                {:refname => "Mac OS X Mountain Lion", :name => "Mac OS X Mountain Lion", :slug => "2012", :category_id => "11"},
                {:refname => "DOS XL", :name => "DOS XL", :slug => null, :category_id => "11"},
                {:refname => "Disk Extended Color Basic", :name => "Disk Extended Color Basic", :slug => null, :category_id => "11"},
                {:refname => "Moblin", :name => "Moblin", :slug => null, :category_id => "11"},
                {:refname => "Cosmos", :name => "Cosmos", :slug => null, :category_id => "11"},
                {:refname => "SINIX", :name => "SINIX", :slug => null, :category_id => "11"},
                {:refname => "SUSE Linux", :name => "SUSE Linux", :slug => "2006", :category_id => "11"},
                {:refname => "ITRON Project", :name => "ITRON Project", :slug => null, :category_id => "11"},
                {:refname => "OpenSUSE", :name => "OpenSUSE", :slug => null, :category_id => "11"},
                {:refname => "FreeBSD 2.2.2", :name => "FreeBSD 2.2.2", :slug => null, :category_id => "11"},
                {:refname => "CSI-DOS", :name => "CSI-DOS", :slug => null, :category_id => "11"},
                {:refname => "PTS-DOS", :name => "PTS-DOS", :slug => null, :category_id => "11"},
                {:refname => "Hikarunix", :name => "Hikarunix", :slug => null, :category_id => "11"},
                {:refname => "Windows Small Business Server 2008", :name => "Windows Small Business Server 2008", :slug => null, :category_id => "11"},
                {:refname => "Windows Essential Business Server 2008", :name => "Windows Essential Business Server 2008", :slug => null, :category_id => "11"},
                {:refname => "BeRTOS", :name => "BeRTOS", :slug => null, :category_id => "11"},
                {:refname => "Jelly Bean", :name => "Jelly Bean", :slug => null, :category_id => "11"},
                {:refname => "Palm OS", :name => "Palm OS", :slug => null, :category_id => "11"},
                {:refname => "TI89", :name => "TI89", :slug => null, :category_id => "11"},
                {:refname => "XrossMediaBar", :name => "XrossMediaBar", :slug => null, :category_id => "11"},
                {:refname => "Android", :name => "Android", :slug => "2008", :category_id => "11"},
                {:refname => "V", :name => "V", :slug => null, :category_id => "11"},
                {:refname => "FreeBSD", :name => "FreeBSD", :slug => null, :category_id => "11"},
                {:refname => "OZONE", :name => "OZONE", :slug => null, :category_id => "11"},
                {:refname => "Vida Linux", :name => "Vida Linux", :slug => null, :category_id => "11"},
                {:refname => "Windows XP 64-bit Edition", :name => "Windows XP 64-bit Edition", :slug => null, :category_id => "11"},
                {:refname => "VM/CMS", :name => "VM/CMS", :slug => null, :category_id => "11"},
                {:refname => "Junos", :name => "Junos", :slug => null, :category_id => "11"},
                {:refname => "NEXTSTEP", :name => "NEXTSTEP", :slug => null, :category_id => "11"},
                {:refname => "DEMOS", :name => "DEMOS", :slug => null, :category_id => "11"},
                {:refname => "Windows 2000 Advanced Server Limited Edition", :name => "Windows 2000 Advanced Server Limited Edition", :slug => null, :category_id => "11"},
                {:refname => "PC DOS 5.0", :name => "PC DOS 5.0", :slug => null, :category_id => "11"},
                {:refname => "Windows 2000 Server", :name => "Windows 2000 Server", :slug => null, :category_id => "11"},
                {:refname => "Windows Server", :name => "Windows Server", :slug => null, :category_id => "11"},
                {:refname => "TRS-DOS", :name => "TRS-DOS", :slug => null, :category_id => "11"},
                {:refname => "PlayStation", :name => "PlayStation", :slug => null, :category_id => "11"},
                {:refname => "OS-9", :name => "OS-9", :slug => null, :category_id => "11"},
                {:refname => "Kubuntu 6.10", :name => "Kubuntu 6.10", :slug => "2006", :category_id => "11"},
                {:refname => "Linpus Linux", :name => "Linpus Linux", :slug => null, :category_id => "11"},
                {:refname => "DC/OSx", :name => "DC/OSx", :slug => null, :category_id => "11"},
                {:refname => "Es", :name => "Es", :slug => null, :category_id => "11"},
                {:refname => "Nintendo DS", :name => "Nintendo DS", :slug => null, :category_id => "11"},
                {:refname => "Amiga Unix", :name => "Amiga Unix", :slug => null, :category_id => "11"},
                {:refname => "Commodore BASIC", :name => "Commodore BASIC", :slug => null, :category_id => "11"},
                {:refname => "Prex", :name => "Prex", :slug => null, :category_id => "11"},
                {:refname => "SunOS", :name => "SunOS", :slug => null, :category_id => "11"},
                {:refname => "Darwin", :name => "Darwin", :slug => null, :category_id => "11"},
                {:refname => "Tinfoil Hat Linux", :name => "Tinfoil Hat Linux", :slug => null, :category_id => "11"},
                {:refname => "Freespire", :name => "Freespire", :slug => null, :category_id => "11"},
                {:refname => "Fedora Core 4", :name => "Fedora Core 4", :slug => null, :category_id => "11"},
                {:refname => "DSPnano RTOS", :name => "DSPnano RTOS", :slug => null, :category_id => "11"},
                {:refname => "NewDos/80", :name => "NewDos/80", :slug => null, :category_id => "11"},
                {:refname => "Java Platform, Micro Edition", :name => "Java Platform, Micro Edition", :slug => null, :category_id => "11"},
                {:refname => "OS/400", :name => "OS/400", :slug => "2006", :category_id => "11"},
                {:refname => "MorphOS", :name => "MorphOS", :slug => null, :category_id => "11"},
                {:refname => "MS-DOS 3.0", :name => "MS-DOS 3.0", :slug => "1984", :category_id => "11"},
                {:refname => "MS-DOS 8.0", :name => "MS-DOS 8.0", :slug => "2000", :category_id => "11"},
                {:refname => "Kubuntu 10.10", :name => "Kubuntu 10.10", :slug => null, :category_id => "11"},
                {:refname => "VPS/VM", :name => "VPS/VM", :slug => null, :category_id => "11"},
                {:refname => "Quark", :name => "Quark", :slug => null, :category_id => "11"},
                {:refname => "FreeBSD 2.x", :name => "FreeBSD 2.x", :slug => null, :category_id => "11"},
                {:refname => "MNOS", :name => "MNOS", :slug => null, :category_id => "11"},
                {:refname => "Kubuntu 8.10", :name => "Kubuntu 8.10", :slug => "2008", :category_id => "11"},
                {:refname => "HDOS", :name => "HDOS", :slug => null, :category_id => "11"},
                {:refname => "Linux Mint", :name => "Linux Mint", :slug => null, :category_id => "11"},
                {:refname => "Test OS", :name => "Test OS", :slug => null, :category_id => "11"},
                {:refname => "Mac OS X v10.5", :name => "Mac OS X v10.5", :slug => "2007", :category_id => "11"},
                {:refname => "Kubuntu 8.04", :name => "Kubuntu 8.04", :slug => "2008", :category_id => "11"},
                {:refname => "SUSE Linux distributions", :name => "SUSE Linux distributions", :slug => null, :category_id => "11"},
                {:refname => "Symbian OS 9.1", :name => "Symbian OS 9.1", :slug => null, :category_id => "11"},
                {:refname => "Windows XP Home Edition", :name => "Windows XP Home Edition", :slug => null, :category_id => "11"},
                {:refname => "Windows Mobile Standard", :name => "Windows Mobile Standard", :slug => null, :category_id => "11"},
                {:refname => "Psion 3", :name => "Psion 3", :slug => null, :category_id => "11"},
                {:refname => "System File", :name => "System File", :slug => null, :category_id => "11"},
                {:refname => "Interix", :name => "Interix", :slug => null, :category_id => "11"},
                {:refname => "Bluebottle OS", :name => "Bluebottle OS", :slug => null, :category_id => "11"},
                {:refname => "MS-DOS", :name => "MS-DOS", :slug => "1981", :category_id => "11"},
                {:refname => "CP-V", :name => "CP-V", :slug => null, :category_id => "11"},
                {:refname => "Venix", :name => "Venix", :slug => null, :category_id => "11"},
                {:refname => "Ubuntu 10.04", :name => "Ubuntu 10.04", :slug => "2010", :category_id => "11"},
                {:refname => "RT-11", :name => "RT-11", :slug => null, :category_id => "11"},
                {:refname => "Windows Server 2008 Standard Edition", :name => "Windows Server 2008 Standard Edition", :slug => null, :category_id => "11"},
                {:refname => "Banyan VINES", :name => "Banyan VINES", :slug => null, :category_id => "11"},
                {:refname => "Safari", :name => "Safari", :slug => null, :category_id => "11"},
                {:refname => "Novell NetWare", :name => "Novell NetWare", :slug => null, :category_id => "11"},
                {:refname => "Pardus", :name => "Pardus", :slug => null, :category_id => "11"},
                {:refname => "Windows 1.0", :name => "Windows 1.0", :slug => null, :category_id => "11"},
                {:refname => "Amstrad CPC", :name => "Amstrad CPC", :slug => null, :category_id => "11"},
                {:refname => "iOS", :name => "iOS", :slug => "2007", :category_id => "11"},
                {:refname => "MINIX 3", :name => "MINIX 3", :slug => null, :category_id => "11"},
                {:refname => "Windows 2000", :name => "Windows 2000", :slug => "2000", :category_id => "11"},
                {:refname => "IX", :name => "IX", :slug => null, :category_id => "11"},
                {:refname => "Firefly BSD", :name => "Firefly BSD", :slug => null, :category_id => "11"},
                {:refname => "Lubuntu", :name => "Lubuntu", :slug => null, :category_id => "11"},
                {:refname => "Singularity", :name => "Singularity", :slug => null, :category_id => "11"},
                {:refname => "FreeBSD 1.0", :name => "FreeBSD 1.0", :slug => null, :category_id => "11"},
                {:refname => "TRAX", :name => "TRAX", :slug => null, :category_id => "11"},
                {:refname => "Commodore DOS", :name => "Commodore DOS", :slug => null, :category_id => "11"},
                {:refname => "ALT Linux", :name => "ALT Linux", :slug => null, :category_id => "11"},
                {:refname => "CP/M", :name => "CP/M", :slug => null, :category_id => "11"},
                {:refname => "MenuetOS", :name => "MenuetOS", :slug => null, :category_id => "11"},
                {:refname => "CatOS", :name => "CatOS", :slug => null, :category_id => "11"},
                {:refname => "PlayStation Portable", :name => "PlayStation Portable", :slug => null, :category_id => "11"},
                {:refname => "FreeBSD 1.1.5.1", :name => "FreeBSD 1.1.5.1", :slug => null, :category_id => "11"},
                {:refname => "GeckOS", :name => "GeckOS", :slug => null, :category_id => "11"},
                {:refname => "Opera", :name => "Opera", :slug => null, :category_id => "11"},
                {:refname => "Nokia N800", :name => "Nokia N800", :slug => null, :category_id => "11"},
                {:refname => "Arch Linux", :name => "Arch Linux", :slug => null, :category_id => "11"},
                {:refname => "Windows Phone 7", :name => "Windows Phone 7", :slug => null, :category_id => "11"},
                {:refname => "FreeDOS", :name => "FreeDOS", :slug => null, :category_id => "11"},
                {:refname => "Scientific Linux", :name => "Scientific Linux", :slug => null, :category_id => "11"},
                {:refname => "Red Flag Linux", :name => "Red Flag Linux", :slug => null, :category_id => "11"},
                {:refname => "House", :name => "House", :slug => null, :category_id => "11"},
                {:refname => "CentOS", :name => "CentOS", :slug => "2007", :category_id => "11"},
                {:refname => "OpenGEU", :name => "OpenGEU", :slug => null, :category_id => "11"},
                {:refname => "LoseThos", :name => "LoseThos", :slug => null, :category_id => "11"},
                {:refname => "Ensemble", :name => "Ensemble", :slug => null, :category_id => "11"},
                {:refname => "Ubuntu 11.10", :name => "Ubuntu 11.10", :slug => "2011", :category_id => "11"},
                {:refname => "Transaction Processing Facility", :name => "Transaction Processing Facility", :slug => null, :category_id => "11"},
                {:refname => "OpenSolaris", :name => "OpenSolaris", :slug => null, :category_id => "11"},
                {:refname => "MiNT", :name => "MiNT", :slug => null, :category_id => "11"},
                {:refname => "Knoppix", :name => "Knoppix", :slug => "2007", :category_id => "11"},
                {:refname => "Kubuntu 10.04", :name => "Kubuntu 10.04", :slug => null, :category_id => "11"},
                {:refname => "BTRON", :name => "BTRON", :slug => null, :category_id => "11"},
                {:refname => "RSTS/E", :name => "RSTS/E", :slug => null, :category_id => "11"},
                {:refname => "EXEC 8", :name => "EXEC 8", :slug => 1964, :category_id => "11"},
                {:refname => "CTRON", :name => "CTRON", :slug => null, :category_id => "11"},
                {:refname => "Domain/OS", :name => "Domain/OS", :slug => null, :category_id => "11"},
                {:refname => "GEOS", :name => "GEOS", :slug => null, :category_id => "11"},
                {:refname => "NetBSD", :name => "NetBSD", :slug => null, :category_id => "11"},
                {:refname => "Windows XP Media Center Edition", :name => "Windows XP Media Center Edition", :slug => null, :category_id => "11"},
                {:refname => "CP/M-86", :name => "CP/M-86", :slug => null, :category_id => "11"},
                {:refname => "SHARE Operating System", :name => "SHARE Operating System", :slug => null, :category_id => "11"},
                {:refname => "USIX", :name => "USIX", :slug => null, :category_id => "11"},
                {:refname => "HelenOS", :name => "HelenOS", :slug => null, :category_id => "11"},
                {:refname => "all", :name => "all", :slug => null, :category_id => "11"},
                {:refname => "Sanos", :name => "Sanos", :slug => null, :category_id => "11"},
                {:refname => "PC DOS 4.0", :name => "PC DOS 4.0", :slug => null, :category_id => "11"},
                {:refname => "Windows CE", :name => "Windows CE", :slug => null, :category_id => "11"},
                {:refname => "Windows 2000 Professional", :name => "Windows 2000 Professional", :slug => null, :category_id => "11"},
                {:refname => "MeeGo", :name => "MeeGo", :slug => "2010", :category_id => "11"},
                {:refname => "M-DOS", :name => "M-DOS", :slug => null, :category_id => "11"},
                {:refname => "Kurumin Linux", :name => "Kurumin Linux", :slug => null, :category_id => "11"},
                {:refname => "Puppy Linux", :name => "Puppy Linux", :slug => null, :category_id => "11"},
                {:refname => "Hivemind", :name => "Hivemind", :slug => null, :category_id => "11"},
                {:refname => "UniFlex", :name => "UniFlex", :slug => null, :category_id => "11"},
                {:refname => "BLAG Linux and GNU", :name => "BLAG Linux and GNU", :slug => null, :category_id => "11"},
                {:refname => "Windows 95", :name => "Windows 95", :slug => "1995", :category_id => "11"},
                {:refname => "MS-DOS 6.0", :name => "MS-DOS 6.0", :slug => "1993", :category_id => "11"},
                {:refname => "MS-DOS 1.25", :name => "MS-DOS 1.25", :slug => "1982", :category_id => "11"},
                {:refname => "MythDora", :name => "MythDora", :slug => null, :category_id => "11"},
                {:refname => "Mac OS X v10.4", :name => "Mac OS X v10.4", :slug => "2005", :category_id => "11"},
                {:refname => "VAXELN", :name => "VAXELN", :slug => null, :category_id => "11"},
                {:refname => "Windows 2.0", :name => "Windows 2.0", :slug => null, :category_id => "11"},
                {:refname => "AtheOS", :name => "AtheOS", :slug => null, :category_id => "11"},
                {:refname => "Integer BASIC", :name => "Integer BASIC", :slug => null, :category_id => "11"},
                {:refname => "Windows XP Professional", :name => "Windows XP Professional", :slug => null, :category_id => "11"},
                {:refname => "Windows Mobile Smartphone", :name => "Windows Mobile Smartphone", :slug => null, :category_id => "11"},
                {:refname => "Windows Vista Enterprise", :name => "Windows Vista Enterprise", :slug => null, :category_id => "11"},
                {:refname => "FutureOS", :name => "FutureOS", :slug => null, :category_id => "11"},
                {:refname => "gOS", :name => "gOS", :slug => null, :category_id => "11"},
                {:refname => "BlackBerry", :name => "BlackBerry", :slug => 1997, :category_id => "11"},
                {:refname => "Midori", :name => "Midori", :slug => null, :category_id => "11"},
                {:refname => "RBM-1", :name => "RBM-1", :slug => null, :category_id => "11"},
                {:refname => "Acorn MOS", :name => "Acorn MOS", :slug => null, :category_id => "11"},
                {:refname => "Openmamba", :name => "Openmamba", :slug => null, :category_id => "11"},
                {:refname => "Mac OS 8", :name => "Mac OS 8", :slug => "1997", :category_id => "11"},
                {:refname => "Psion 5", :name => "Psion 5", :slug => null, :category_id => "11"},
                {:refname => "PS2 Linux", :name => "PS2 Linux", :slug => null, :category_id => "11"},
                {:refname => "RISC/os", :name => "RISC/os", :slug => null, :category_id => "11"},
                {:refname => "GNU Mach", :name => "GNU Mach", :slug => null, :category_id => "11"},
                {:refname => "Nemesis", :name => "Nemesis", :slug => null, :category_id => "11"},
                {:refname => "Minix-vmd", :name => "Minix-vmd", :slug => null, :category_id => "11"},
                {:refname => "MeikOS", :name => "MeikOS", :slug => null, :category_id => "11"},
                {:refname => "BlackBerry Tablet OS", :name => "BlackBerry Tablet OS", :slug => null, :category_id => "11"},
                {:refname => "GNU Hurd", :name => "GNU Hurd", :slug => null, :category_id => "11"},
                {:refname => "TOPS-10", :name => "TOPS-10", :slug => null, :category_id => "11"},
                {:refname => "Soft Hard Real-Time Kernel", :name => "Soft Hard Real-Time Kernel", :slug => null, :category_id => "11"},
                {:refname => "FreeBSD 1.x", :name => "FreeBSD 1.x", :slug => null, :category_id => "11"},
                {:refname => "IBM AIX", :name => "IBM AIX", :slug => 1986, :category_id => "11"}]}




################################################################################################
################################################################################################
##########                            Web Browsers Data                          ###############
################################################################################################
################################################################################################


#Seeding Web Browsers
Product.create [{:name => "Google Chrome OS", :slug => "Google Chrome OS", :category_id => "13"},
                {:name => "Flock", :slug => "Flock", :category_id => "13"},
                {:name => "Netscape", :slug => "Netscape", :category_id => "13"},
                {:name => "Dillo", :slug => "Dillo", :category_id => "13"},
                {:name => "SPIN", :slug => "SPIN", :category_id => "13"},
                {:name => "Oregano", :slug => "Oregano", :category_id => "13"},
                {:name => "Internet Explorer 9", :slug => "Internet Explorer 9", :category_id => "13"},
                {:name => "Arachne", :slug => "Arachne", :category_id => "13"},
                {:name => "Internet Explorer for Mac", :slug => "Internet Explorer for Mac", :category_id => "13"},
                {:name => "RockMelt", :slug => "RockMelt", :category_id => "13"},
                {:name => "Uzbl", :slug => "Uzbl", :category_id => "13"},
                {:name => "Netscape Browser", :slug => "Netscape Browser", :category_id => "13"},
                {:name => "Arora", :slug => "Arora", :category_id => "13"},
                {:name => "Arena", :slug => "Arena", :category_id => "13"},
                {:name => "Charon", :slug => "Charon", :category_id => "13"},
                {:name => "PlayStation Portable web browser", :slug => "PlayStation Portable web browser", :category_id => "13"},
                {:name => "Mozilla Firefox", :slug => "Mozilla Firefox", :category_id => "13"},
                {:name => "Google Chrome", :slug => "Google Chrome", :category_id => "13"},
                {:name => "SlipKnot", :slug => "SlipKnot", :category_id => "13"},
                {:name => "ICab", :slug => "ICab", :category_id => "13"},
                {:name => "Swift", :slug => "Swift", :category_id => "13"},
                {:name => "Netscape Navigator", :slug => "Netscape Navigator", :category_id => "13"},
                {:name => "Salamander", :slug => "Salamander", :category_id => "13"},
                {:name => "Internet Explorer", :slug => "Internet Explorer", :category_id => "13"},
                {:name => "Abaco", :slug => "Abaco", :category_id => "13"},
                {:name => "surf", :slug => "surf", :category_id => "13"},
                {:name => "Voyager", :slug => "Voyager", :category_id => "13"},
                {:name => "Yahoo Axis", :slug => "Yahoo Axis", :category_id => "13"},
                {:name => "Konqueror", :slug => "Konqueror", :category_id => "13"},
                {:name => "Netscape Communicator", :slug => "Netscape Communicator", :category_id => "13"},
                {:name => "Midori", :slug => "Midori", :category_id => "13"},
                {:name => "Web Browser for S60", :slug => "Web Browser for S60", :category_id => "13"},
                {:name => "Opera Mobile", :slug => "Opera Mobile", :category_id => "13"},
                {:name => "Mosaic", :slug => "Mosaic", :category_id => "13"},
                {:name => "Wii Browser", :slug => "Wii Browser", :category_id => "13"},
                {:name => "luakit", :slug => "luakit", :category_id => "13"},
                {:name => "jumanji", :slug => "jumanji", :category_id => "13"},
                {:name => "3B", :slug => "3B", :category_id => "13"},
                {:name => "Mothra", :slug => "Mothra", :category_id => "13"},
                {:name => "SeaMonkey", :slug => "SeaMonkey", :category_id => "13"},
                {:name => "Links", :slug => "Links", :category_id => "13"},
                {:name => "Chromium", :slug => "Chromium", :category_id => "13"},
                {:name => "Camino", :slug => "Camino", :category_id => "13"},
                {:name => "Cello", :slug => "Cello", :category_id => "13"},
                {:name => "Conkeror", :slug => "Conkeror", :category_id => "13"},
                {:name => "Ozone", :slug => "Ozone", :category_id => "13"},
                {:name => "Konqueror Embedded", :slug => "Konqueror Embedded", :category_id => "13"},
                {:name => "Epiphany", :slug => "Epiphany", :category_id => "13"},
                {:name => "Grail", :slug => "Grail", :category_id => "13"},
                {:name => "Internet Explorer 8", :slug => "Internet Explorer 8", :category_id => "13"},
                {:name => "Sleipnir", :slug => "Sleipnir", :category_id => "13"},
                {:name => "Lynx", :slug => "Lynx", :category_id => "13"},
                {:name => "NetFront", :slug => "NetFront", :category_id => "13"},
                {:name => "Amaya", :slug => "Amaya", :category_id => "13"},
                {:name => "Opera", :slug => "Opera", :category_id => "13"},
                {:name => "Safari", :slug => "Safari", :category_id => "13"},
                {:name => "Shiira", :slug => "Shiira", :category_id => "13"},
                {:name => "Opera Mini", :slug => "Opera Mini", :category_id => "13"},
                {:name => "Avant Browser", :slug => "Avant Browser", :category_id => "13"},
                {:name => "Blazer", :slug => "Blazer", :category_id => "13"}]}



################################################################################################
################################################################################################
##########                     Programming Languages Data                        ###############
################################################################################################
################################################################################################


